/*
  Source code is in UTF-8 encoding. The following symbols may appear, among others:
  α β γ δ ε ζ η θ ι κ λ μ ν ξ ο π ρ ς σ τ υ φ χ ψ ω « • ¦ » ∀ ∃ ∷ … → ← ﬁ ﬂ ƒ
  If you can't read this, you're out of luck. This code was generated with the frege compiler version 3.24.100
  from src/main/frege/io/github/mchav/freoquiz/CheatActivity.fr Do not edit this file!
  Instead, edit the source file and recompile.
*/

package io.github.mchav.freoquiz;

import frege.run7.Func;
import frege.run7.Lazy;
import frege.run7.Thunk;
import frege.run.Kind;
import frege.run.RunTM;
import frege.runtime.Meta;
import frege.runtime.Phantom.RealWorld;
import frege.Prelude;
import frege.control.Category;
import frege.control.Semigroupoid;
import frege.java.IO;
import frege.java.Lang;
import frege.java.Util;
import frege.java.util.Regex;
import frege.prelude.Maybe;
import frege.prelude.PreludeArrays;
import frege.prelude.PreludeBase;
import frege.prelude.PreludeIO;
import frege.prelude.PreludeList;
import frege.prelude.PreludeMonad;
import frege.prelude.PreludeText;
import froid.Types;
import froid.app.Activity;
import froid.content.Context;
import froid.content.Intent;
import froid.view.View;
import froid.widget.Button;
import froid.widget.TextView;
import froid.widget.Toast;
import froid.widget.Toolbar;

@SuppressWarnings("unused")
@Meta.FregePackage(
  source="src\\main\\frege\\io\\github\\mchav\\freoquiz\\CheatActivity.fr", time=1482302726867L, jmajor=1,
  jminor=7,
  imps={
    "froid.app.Activity", "froid.widget.Button", "froid.content.Context", "froid.content.Intent", "frege.Prelude",
    "frege.prelude.PreludeArrays", "frege.prelude.PreludeBase", "frege.prelude.PreludeIO", "frege.prelude.PreludeList",
    "frege.prelude.PreludeMonad", "frege.prelude.PreludeText", "frege.java.util.Regex", "froid.widget.TextView",
    "froid.widget.Toast", "froid.view.View"
  },
  nmss={
    "Activity", "Button", "Context", "Intent", "Prelude", "PreludeArrays", "PreludeBase", "PreludeIO",
    "PreludeList", "PreludeMonad", "PreludeText", "Regexp", "TextView", "Toast", "View"
  },
  symas={}, symcs={}, symis={}, symts={},
  symvs={
    @Meta.SymV(
      offset=1217, name=@Meta.QName(pack="io.github.mchav.freoquiz.CheatActivity", base="wasAnswerShown"), stri="s(s)",
      sig=1, depth=1, rkind=49
    ),
    @Meta.SymV(
      offset=474, name=@Meta.QName(pack="io.github.mchav.freoquiz.CheatActivity", base="showAnswerButtonId"), stri="s",
      sig=2, nativ="io.github.mchav.freoquiz.R.id.showAnswerButton", pur=true, depth=0, rkind=33
    ),
    @Meta.SymV(
      offset=1337, name=@Meta.QName(pack="io.github.mchav.freoquiz.CheatActivity", base="setAnswerShownResult"),
      stri="s(uu)", sig=5, depth=2, rkind=49
    ),
    @Meta.SymV(
      offset=1570, name=@Meta.QName(pack="io.github.mchav.freoquiz.CheatActivity", base="onCreate"), stri="s(s)",
      sig=6, depth=1, rkind=49
    ),
    @Meta.SymV(
      offset=1031, name=@Meta.QName(pack="io.github.mchav.freoquiz.CheatActivity", base="newIntent"), stri="s(su)",
      sig=8, depth=2, rkind=49
    ),
    @Meta.SymV(
      offset=632, name=@Meta.QName(pack="io.github.mchav.freoquiz.CheatActivity", base="extraAnswerIsTrue"), stri="s",
      sig=9, depth=0, rkind=49
    ),
    @Meta.SymV(
      offset=695, name=@Meta.QName(pack="io.github.mchav.freoquiz.CheatActivity", base="extraAnswerShown"), stri="s",
      sig=9, depth=0, rkind=49
    ),
    @Meta.SymV(
      offset=304, name=@Meta.QName(pack="io.github.mchav.freoquiz.CheatActivity", base="cheatActivity"), stri="s",
      sig=10, nativ="io.github.mchav.freoquiz.CheatActivity.class", pur=true, depth=0, rkind=33
    ),
    @Meta.SymV(
      offset=757, name=@Meta.QName(pack="io.github.mchav.freoquiz.CheatActivity", base="cheatHandler"), stri="s(ussu)",
      sig=13, depth=4, rkind=49
    ),
    @Meta.SymV(
      offset=562, name=@Meta.QName(pack="io.github.mchav.freoquiz.CheatActivity", base="answerTextId"), stri="s",
      sig=2, nativ="io.github.mchav.freoquiz.R.id.answerTextView", pur=true, depth=0, rkind=33
    ),
    @Meta.SymV(
      offset=389, name=@Meta.QName(pack="io.github.mchav.freoquiz.CheatActivity", base="activityCheat"), stri="s",
      sig=2, nativ="io.github.mchav.freoquiz.R.layout.activity_cheat", pur=true, depth=0,
      rkind=33
    )
  },
  symls={},
  taus={
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeIO", base="Mutable")}),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="RealWorld")}),
    @Meta.Tau(kind=0, suba=0, subb=1),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="froid.content.Intent", base="Intent")}),
    @Meta.Tau(kind=0, suba=2, subb=3),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="ST")}),
    @Meta.Tau(kind=0, suba=5, subb=1),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="Bool")}),
    @Meta.Tau(kind=0, suba=6, subb=7),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="Int")}),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="froid.app.Activity", base="Activity")}),
    @Meta.Tau(kind=0, suba=2, subb=10),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="()")}),
    @Meta.Tau(kind=0, suba=6, subb=12),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="froid.content.Context", base="Context")}),
    @Meta.Tau(kind=0, suba=2, subb=14), @Meta.Tau(kind=0, suba=6, subb=4),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="StringJ")}),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="Char")}),
    @Meta.Tau(kind=0, suba=17, subb=18),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="Class")}),
    @Meta.Tau(kind=9), @Meta.Tau(suba=21, tvar="a"), @Meta.Tau(kind=0, suba=20, subb=22),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="froid.view.View", base="View")}),
    @Meta.Tau(kind=0, suba=2, subb=24),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="froid.widget.TextView", base="TextView")}),
    @Meta.Tau(kind=0, suba=2, subb=26)
  },
  rhos={
    @Meta.Rho(rhofun=false, rhotau=4), @Meta.Rho(rhofun=false, rhotau=8), @Meta.Rho(sigma=0, rhotau=1),
    @Meta.Rho(rhofun=false, rhotau=9), @Meta.Rho(rhofun=false, rhotau=11), @Meta.Rho(rhofun=false, rhotau=7),
    @Meta.Rho(rhofun=false, rhotau=13), @Meta.Rho(sigma=4, rhotau=6), @Meta.Rho(sigma=3, rhotau=7),
    @Meta.Rho(sigma=3, rhotau=6), @Meta.Rho(rhofun=false, rhotau=15), @Meta.Rho(rhofun=false, rhotau=16),
    @Meta.Rho(sigma=4, rhotau=11), @Meta.Rho(sigma=7, rhotau=12), @Meta.Rho(rhofun=false, rhotau=19),
    @Meta.Rho(rhofun=false, rhotau=23), @Meta.Rho(rhofun=false, rhotau=25), @Meta.Rho(rhofun=false, rhotau=27),
    @Meta.Rho(sigma=11, rhotau=6), @Meta.Rho(sigma=4, rhotau=18), @Meta.Rho(sigma=12, rhotau=19),
    @Meta.Rho(sigma=11, rhotau=20)
  },
  sigmas={
    @Meta.Sigma(rho=0), @Meta.Sigma(rho=2), @Meta.Sigma(rho=3), @Meta.Sigma(rho=4), @Meta.Sigma(rho=5),
    @Meta.Sigma(rho=8), @Meta.Sigma(rho=9), @Meta.Sigma(rho=10), @Meta.Sigma(rho=13), @Meta.Sigma(rho=14),
    @Meta.Sigma(bound={"a"}, kinds={21}, rho=15), @Meta.Sigma(rho=16), @Meta.Sigma(rho=17), @Meta.Sigma(rho=21)
  },
  exprs={@Meta.Expr()}
)
final public class CheatActivity extends froid.app.FregeActivity  {
  




final public static String/*<Character>*/ extraAnswerShown = "io.github.mchav.geoquiz.answer_shown";
final public static Func.U<RealWorld, Boolean> wasAnswerShown(final android.content.Intent arg$1) {
  return Intent.TIntent.getBooleanExtra(arg$1, CheatActivity.extraAnswerShown, false);
}
final public static Func.U<RealWorld, Short> setAnswerShownResult(
  final Lazy<froid.app.FregeActivity> arg$1, final Lazy<Boolean> arg$2
) {
  final Func.U<RealWorld, android.content.Intent> v2038$7833 = Intent.TIntent.newα(PreludeBase.TUnit.Unit);
  return new Func.U.D<RealWorld, Short>() {
        public Lazy<Short> apply(final Lazy<RealWorld> arg$8103) {
          final android.content.Intent v2041$7836 = v2038$7833.apply(arg$8103).call();
          final Func.U<RealWorld, Short> v4801$7858 = Intent.TIntent.putExtra(
                v2041$7836, CheatActivity.extraAnswerShown, (boolean)arg$2.call()
              );
          final short v4804$7860 = (short)v4801$7858.apply(arg$8103).call();
          final Func.U<RealWorld, Short> v4805$7861 = Thunk.<Func.U<RealWorld, Short>>shared(
                new Lazy.D<Func.U<RealWorld, Short>>() {
                  public Func.U<RealWorld, Short> call() {
                    return Activity.TActivity.setResult(arg$1.call(), android.app.Activity.RESULT_OK, v2041$7836);
                  }
                }
              ).call();
          return Thunk.<Short>nested(
                    new Lazy.D<Lazy<Short>>() {
                      public Lazy<Short> call() {
                        return v4805$7861.apply(arg$8103);
                      }
                    }
                  );
        }
      };
}
final public static String/*<Character>*/ extraAnswerIsTrue = "io.github.mchav.freoquiz.answer_is_true";
final public static Func.U<RealWorld, Short> cheatHandler(
  final Lazy<android.view.View> arg$1, final android.widget.TextView arg$2, final boolean arg$3,
  final Lazy<android.view.View> arg$4
) {
  final Func.U<RealWorld, Short> v4801$8086 = TextView.TTextView.setVisibility(arg$2, android.view.View.VISIBLE);
  final Func.U<RealWorld, Short> v4801$8062 = TextView.TTextView.setText(arg$2, arg$3 == true ? "True" : "False");
  return new Func.U.D<RealWorld, Short>() {
        public Lazy<Short> apply(final Lazy<RealWorld> arg$8113) {
          final short v4804$8064 = (short)v4801$8062.apply(arg$8113).call();
          final Func.U<RealWorld, Short> v4805$8065 = (new Func.U.D<RealWorld, Short>() {
            public Lazy<Short> apply(final Lazy<RealWorld> arg$8109) {
              final short v4804$8088 = (short)v4801$8086.apply(arg$8109).call();
              final Func.U<RealWorld, Short> v4805$8089 = Thunk.<Func.U<RealWorld, Short>>shared(
                    new Lazy.D<Func.U<RealWorld, Short>>() {
                      public Func.U<RealWorld, Short> call() {
                        return View.TView.setVisibility(arg$1.call(), android.view.View.INVISIBLE);
                      }
                    }
                  ).call();
              return Thunk.<Short>nested(
                        new Lazy.D<Lazy<Short>>() {
                          public Lazy<Short> call() {
                            return v4805$8089.apply(arg$8109);
                          }
                        }
                      );
            }
          }).call();
          return Thunk.<Short>nested(
                    new Lazy.D<Lazy<Short>>() {
                      public Lazy<Short> call() {
                        return v4805$8065.apply(arg$8113);
                      }
                    }
                  );
        }
      };
}
@SuppressWarnings("unchecked") final public static <𝓐> Class<𝓐> cheatActivity() {
  return (Class<𝓐>)io.github.mchav.freoquiz.CheatActivity.class;
}
final public static Func.U<RealWorld, android.content.Intent> newIntent(
  final android.content.Context arg$1, final Lazy<Boolean> arg$2
) {
  final Func.U<RealWorld, android.content.Intent> v2038$8013 = Intent.TIntent.<Void>newβ(
        arg$1, CheatActivity.<Void>cheatActivity()
      );
  return new Func.U.D<RealWorld, android.content.Intent>() {
        public Lazy<android.content.Intent> apply(final Lazy<RealWorld> arg$8117) {
          final android.content.Intent v2041$8016 = v2038$8013.apply(arg$8117).call();
          final Func.U<RealWorld, Short> v4801$8038 = Intent.TIntent.putExtra(
                v2041$8016, CheatActivity.extraAnswerIsTrue, (boolean)arg$2.call()
              );
          final short v4804$8040 = (short)v4801$8038.apply(arg$8117).call();
          final Func.U<RealWorld, android.content.Intent> v4805$8041 = Thunk.<Func.U<RealWorld, android.content.Intent>>shared(
                new Lazy.D<Func.U<RealWorld, android.content.Intent>>() {
                  public Func.U<RealWorld, android.content.Intent> call() {
                    return PreludeMonad.IMonad_ST.<RealWorld, android.content.Intent>pure(
                              Thunk.<android.content.Intent>lazy(v2041$8016)
                            );
                  }
                }
              ).call();
          return Thunk.<android.content.Intent>nested(
                    new Lazy.D<Lazy<android.content.Intent>>() {
                      public Lazy<android.content.Intent> call() {
                        return v4805$8041.apply(arg$8117);
                      }
                    }
                  );
        }
      };
}
final public static Func.U<RealWorld, Short> onCreate(final froid.app.FregeActivity arg$1) {
  final Func.U<RealWorld, android.content.Context> v2038$7879 = Activity.TActivity.getApplicationContext(
        arg$1
      );
  return new Func.U.D<RealWorld, Short>() {
        public Lazy<Short> apply(final Lazy<RealWorld> arg$8123) {
          final android.content.Context v2041$7882 = v2038$7879.apply(arg$8123).call();
          final Func.U<RealWorld, android.content.Intent> v2038$7925 = Activity.TActivity.getIntent(
                arg$1
              );
          final Func.U<RealWorld, Short> v4801$7904 = Activity.TActivity.setContentView(
                arg$1, io.github.mchav.freoquiz.R.layout.activity_cheat
              );
          final short v4804$7906 = (short)v4801$7904.apply(arg$8123).call();
          final Func.U<RealWorld, Short> v4805$7907 = (new Func.U.D<RealWorld, Short>() {
            public Lazy<Short> apply(final Lazy<RealWorld> arg$8126) {
              final android.content.Intent v2041$7928 = v2038$7925.apply(arg$8126).call();
              final Func.U<RealWorld, Boolean> v2038$7947 = Intent.TIntent.getBooleanExtra(
                    v2041$7928, CheatActivity.extraAnswerIsTrue, false
                  );
              final boolean v2041$7950 = (boolean)v2038$7947.apply(arg$8126).call();
              final Func.U<RealWorld, android.widget.TextView> v2038$7969 = TextView.asTextView(
                    arg$1, io.github.mchav.freoquiz.R.id.answerTextView
                  );
              final android.widget.TextView v2041$7972 = v2038$7969.apply(arg$8126).call();
              final Func.U<RealWorld, android.view.View> v2038$7991 = Activity.TActivity.findViewById(
                    arg$1, io.github.mchav.freoquiz.R.id.showAnswerButton
                  );
              final android.view.View v2041$7994 = v2038$7991.apply(arg$8126).call();
              final Func.U<RealWorld, Short> v2042$7995 = View.setOnClick(
                    v2041$7994,
                    new Func.U.D<android.view.View, Func.U<RealWorld, Short>>() {
                      public Lazy<Func.U<RealWorld, Short>> apply(final Lazy<android.view.View> η$8134) {
                        return Thunk.<Func.U<RealWorld, Short>>shared(
                                  new Lazy.D<Func.U<RealWorld, Short>>() {
                                    public Func.U<RealWorld, Short> call() {
                                      return CheatActivity.cheatHandler(
                                                Thunk.<android.view.View>lazy(v2041$7994), v2041$7972,
                                                v2041$7950, η$8134
                                              );
                                    }
                                  }
                                );
                      }
                    }
                  );
              return Thunk.<Short>nested(
                        new Lazy.D<Lazy<Short>>() {
                          public Lazy<Short> call() {
                            return v2042$7995.apply(arg$8126);
                          }
                        }
                      );
            }
          }).call();
          return Thunk.<Short>nested(
                    new Lazy.D<Lazy<Short>>() {
                      public Lazy<Short> call() {
                        return v4805$7907.apply(arg$8123);
                      }
                    }
                  );
        }
      };
}

}
