/*
  Source code is in UTF-8 encoding. The following symbols may appear, among others:
  α β γ δ ε ζ η θ ι κ λ μ ν ξ ο π ρ ς σ τ υ φ χ ψ ω « • ¦ » ∀ ∃ ∷ … → ← ﬁ ﬂ ƒ
  If you can't read this, you're out of luck. This code was generated with the frege compiler version 3.24.100
  from src/main/frege/io/github/mchav/freoquiz/MainActivity.fr Do not edit this file!
  Instead, edit the source file and recompile.
*/

package io.github.mchav.freoquiz;

import frege.run7.Func;
import frege.run7.Lazy;
import frege.run7.Thunk;
import frege.run.Kind;
import frege.run.RunTM;
import frege.runtime.Meta;
import frege.runtime.Phantom.RealWorld;
import frege.Prelude;
import frege.control.Category;
import frege.control.Semigroupoid;
import frege.data.List;
import frege.java.IO;
import frege.java.Lang;
import frege.java.Util;
import frege.java.util.Regex;
import frege.prelude.Maybe;
import frege.prelude.PreludeArrays;
import frege.prelude.PreludeBase;
import frege.prelude.PreludeIO;
import frege.prelude.PreludeList;
import frege.prelude.PreludeMonad;
import frege.prelude.PreludeText;
import froid.Types;
import froid.app.Activity;
import froid.content.Context;
import froid.content.Intent;
import froid.view.View;
import froid.widget.Button;
import froid.widget.TextView;
import froid.widget.Toast;
import froid.widget.Toolbar;
import io.github.mchav.freoquiz.CheatActivity;

@SuppressWarnings("unused")
@Meta.FregePackage(
  source="src\\main\\frege\\io\\github\\mchav\\freoquiz\\MainActivity.fr", time=1482302729200L, jmajor=1,
  jminor=7,
  imps={
    "froid.app.Activity", "froid.widget.Button", "io.github.mchav.freoquiz.CheatActivity", "froid.content.Context",
    "frege.data.List", "frege.Prelude", "frege.prelude.PreludeArrays", "frege.prelude.PreludeBase",
    "frege.prelude.PreludeIO", "frege.prelude.PreludeList", "frege.prelude.PreludeMonad", "frege.prelude.PreludeText",
    "frege.java.util.Regex", "froid.widget.TextView", "froid.widget.Toast", "froid.view.View"
  },
  nmss={
    "Activity", "Button", "CheatActivity", "Context", "List", "Prelude", "PreludeArrays", "PreludeBase",
    "PreludeIO", "PreludeList", "PreludeMonad", "PreludeText", "Regexp", "TextView", "Toast",
    "View"
  },
  symas={}, symcs={}, symis={},
  symts={
    @Meta.SymT(
      offset=922, name=@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.MainActivity", base="Question"), typ=0,
      kind=5,
      cons={
        @Meta.SymD(
          offset=933,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.MainActivity", base="Question", member="Question"),
          cid=0, typ=3,
          fields={
            @Meta.Field(name="text", offset=944, sigma=1, strict=false),
            @Meta.Field(name="answer", offset=960, sigma=2, strict=false)
          }
        )
      },
      lnks={},
      funs={
        @Meta.SymV(
          offset=945,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.MainActivity", base="Question", member="upd$text"),
          stri="s(su)", sig=4, depth=2, rkind=49, doc="update field @text@"
        ),
        @Meta.SymV(
          offset=945,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.MainActivity", base="Question", member="has$text"),
          stri="s(u)", sig=6, depth=1, rkind=49, doc="check if constructor has field @text@"
        ),
        @Meta.SymV(
          offset=945,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.MainActivity", base="Question", member="text"),
          stri="s(s)", sig=7, depth=1, rkind=49, doc="access field @text@"
        ),
        @Meta.SymV(
          offset=961,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.MainActivity", base="Question", member="upd$answer"),
          stri="s(su)", sig=8, depth=2, rkind=49, doc="update field @answer@"
        ),
        @Meta.SymV(
          offset=945,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.MainActivity", base="Question", member="chg$text"),
          stri="s(ss)", sig=10, depth=2, rkind=49, doc="change field @text@"
        ),
        @Meta.SymV(
          offset=961,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.MainActivity", base="Question", member="chg$answer"),
          stri="s(ss)", sig=12, depth=2, rkind=49, doc="change field @answer@"
        ),
        @Meta.SymV(
          offset=961,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.MainActivity", base="Question", member="answer"),
          stri="s(s)", sig=13, depth=1, rkind=49, doc="access field @answer@"
        ),
        @Meta.SymV(
          offset=961,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.MainActivity", base="Question", member="has$answer"),
          stri="s(u)", sig=6, depth=1, rkind=49, doc="check if constructor has field @answer@"
        )
      },
      prod=true
    )
  },
  symvs={
    @Meta.SymV(
      offset=1947, name=@Meta.QName(pack="io.github.mchav.freoquiz.MainActivity", base="sequenceQuestions"),
      stri="s(s)", sig=15, depth=1, rkind=49
    ),
    @Meta.SymV(
      offset=350, name=@Meta.QName(pack="io.github.mchav.freoquiz.MainActivity", base="requestCheatCode"), stri="s",
      sig=16, depth=0, rkind=49
    ),
    @Meta.SymV(
      offset=848, name=@Meta.QName(pack="io.github.mchav.freoquiz.MainActivity", base="questionText"), stri="s",
      sig=16, nativ="io.github.mchav.freoquiz.R.id.question_text", pur=true, depth=0, rkind=33
    ),
    @Meta.SymV(
      offset=980, name=@Meta.QName(pack="io.github.mchav.freoquiz.MainActivity", base="questions"), stri="s",
      sig=14, depth=0, rkind=49
    ),
    @Meta.SymV(
      offset=1821, name=@Meta.QName(pack="io.github.mchav.freoquiz.MainActivity", base="previousQuestion"), stri="s(s)",
      sig=17, depth=1, rkind=49
    ),
    @Meta.SymV(
      offset=3235, name=@Meta.QName(pack="io.github.mchav.freoquiz.MainActivity", base="onCreate"), stri="s(s)",
      sig=19, depth=1, rkind=49
    ),
    @Meta.SymV(
      offset=1714, name=@Meta.QName(pack="io.github.mchav.freoquiz.MainActivity", base="nextQuestion"), stri="s(s)",
      sig=17, depth=1, rkind=49
    ),
    @Meta.SymV(
      offset=2967, name=@Meta.QName(pack="io.github.mchav.freoquiz.MainActivity", base="navigationHandler"),
      stri="s(uuuu)", sig=23, depth=4, rkind=49
    ),
    @Meta.SymV(
      offset=2160, name=@Meta.QName(pack="io.github.mchav.freoquiz.MainActivity", base="handler"), stri="s(uuuu)",
      sig=23, depth=4, rkind=49
    ),
    @Meta.SymV(
      offset=2585, name=@Meta.QName(pack="io.github.mchav.freoquiz.MainActivity", base="cheatHandler"), stri="s(uuuu)",
      sig=24, depth=4, rkind=49
    ),
    @Meta.SymV(
      offset=706, name=@Meta.QName(pack="io.github.mchav.freoquiz.MainActivity", base="btnTrueId"), stri="s",
      sig=16, nativ="io.github.mchav.freoquiz.R.id.btnTrue", pur=true, depth=0, rkind=33
    ),
    @Meta.SymV(
      offset=494, name=@Meta.QName(pack="io.github.mchav.freoquiz.MainActivity", base="btnPrevId"), stri="s",
      sig=16, nativ="io.github.mchav.freoquiz.R.id.btnPrev", pur=true, depth=0, rkind=33
    ),
    @Meta.SymV(
      offset=634, name=@Meta.QName(pack="io.github.mchav.freoquiz.MainActivity", base="btnFalseId"), stri="s",
      sig=16, nativ="io.github.mchav.freoquiz.R.id.btnFalse", pur=true, depth=0, rkind=33
    ),
    @Meta.SymV(
      offset=776, name=@Meta.QName(pack="io.github.mchav.freoquiz.MainActivity", base="btnCheatId"), stri="s",
      sig=16, nativ="io.github.mchav.freoquiz.R.id.btnCheat", pur=true, depth=0, rkind=33
    ),
    @Meta.SymV(
      offset=564, name=@Meta.QName(pack="io.github.mchav.freoquiz.MainActivity", base="btnNextId"), stri="s",
      sig=16, nativ="io.github.mchav.freoquiz.R.id.btnNext", pur=true, depth=0, rkind=33
    ),
    @Meta.SymV(
      offset=411, name=@Meta.QName(pack="io.github.mchav.freoquiz.MainActivity", base="activityMain"), stri="s",
      sig=16, nativ="io.github.mchav.freoquiz.R.layout.activity_main", pur=true, depth=0,
      rkind=33
    )
  },
  symls={
    @Meta.SymL(
      offset=933, name=@Meta.QName(pack="io.github.mchav.freoquiz.MainActivity", base="Question"),
      alias=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.MainActivity", base="Question", member="Question")
    )
  },
  taus={
    @Meta.Tau(
      kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.MainActivity", base="Question")}
    ),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="StringJ")}),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="Char")}),
    @Meta.Tau(kind=0, suba=1, subb=2),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="Bool")}),
    @Meta.Tau(kind=9), @Meta.Tau(suba=5, tvar="α"),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="->")}),
    @Meta.Tau(kind=0, suba=7, subb=3), @Meta.Tau(kind=0, suba=8, subb=3), @Meta.Tau(kind=0, suba=7, subb=4),
    @Meta.Tau(kind=0, suba=10, subb=4),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="[]")}),
    @Meta.Tau(kind=0, suba=12, subb=0),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="(,)")}),
    @Meta.Tau(kind=0, suba=14, subb=3), @Meta.Tau(kind=0, suba=15, subb=3), @Meta.Tau(kind=0, suba=12, subb=16),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="Int")}),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeIO", base="Mutable")}),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="RealWorld")}),
    @Meta.Tau(kind=0, suba=19, subb=20),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="froid.app.Activity", base="Activity")}),
    @Meta.Tau(kind=0, suba=21, subb=22),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="ST")}),
    @Meta.Tau(kind=0, suba=24, subb=20),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="()")}),
    @Meta.Tau(kind=0, suba=25, subb=26),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="froid.content.Context", base="Context")}),
    @Meta.Tau(kind=0, suba=21, subb=28),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="froid.widget.TextView", base="TextView")}),
    @Meta.Tau(kind=0, suba=21, subb=30),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="froid.view.View", base="View")}),
    @Meta.Tau(kind=0, suba=21, subb=32)
  },
  rhos={
    @Meta.Rho(rhofun=false, rhotau=0), @Meta.Rho(rhofun=false, rhotau=3), @Meta.Rho(rhofun=false, rhotau=4),
    @Meta.Rho(sigma=2, rhotau=0), @Meta.Rho(sigma=1, rhotau=3), @Meta.Rho(sigma=1, rhotau=0),
    @Meta.Rho(sigma=0, rhotau=5), @Meta.Rho(rhofun=false, rhotau=6), @Meta.Rho(sigma=5, rhotau=2),
    @Meta.Rho(sigma=0, rhotau=1), @Meta.Rho(sigma=0, rhotau=3), @Meta.Rho(rhofun=false, rhotau=9),
    @Meta.Rho(sigma=9, rhotau=0), @Meta.Rho(sigma=0, rhotau=12), @Meta.Rho(rhofun=false, rhotau=11),
    @Meta.Rho(sigma=11, rhotau=0), @Meta.Rho(sigma=0, rhotau=15), @Meta.Rho(sigma=0, rhotau=2),
    @Meta.Rho(rhofun=false, rhotau=13), @Meta.Rho(rhofun=false, rhotau=17), @Meta.Rho(sigma=14, rhotau=19),
    @Meta.Rho(rhofun=false, rhotau=18), @Meta.Rho(sigma=1, rhotau=1), @Meta.Rho(rhofun=false, rhotau=23),
    @Meta.Rho(rhofun=false, rhotau=27), @Meta.Rho(sigma=18, rhotau=24), @Meta.Rho(rhofun=false, rhotau=29),
    @Meta.Rho(rhofun=false, rhotau=31), @Meta.Rho(rhofun=false, rhotau=33), @Meta.Rho(sigma=22, rhotau=24),
    @Meta.Rho(sigma=2, rhotau=29), @Meta.Rho(sigma=21, rhotau=30), @Meta.Rho(sigma=20, rhotau=31),
    @Meta.Rho(sigma=21, rhotau=29), @Meta.Rho(sigma=20, rhotau=33), @Meta.Rho(sigma=18, rhotau=34)
  },
  sigmas={
    @Meta.Sigma(rho=0), @Meta.Sigma(rho=1), @Meta.Sigma(rho=2), @Meta.Sigma(rho=4), @Meta.Sigma(rho=6),
    @Meta.Sigma(rho=7), @Meta.Sigma(bound={"α"}, kinds={5}, rho=8), @Meta.Sigma(rho=9), @Meta.Sigma(rho=10),
    @Meta.Sigma(rho=11), @Meta.Sigma(rho=13), @Meta.Sigma(rho=14), @Meta.Sigma(rho=16), @Meta.Sigma(rho=17),
    @Meta.Sigma(rho=18), @Meta.Sigma(rho=20), @Meta.Sigma(rho=21), @Meta.Sigma(rho=22), @Meta.Sigma(rho=23),
    @Meta.Sigma(rho=25), @Meta.Sigma(rho=26), @Meta.Sigma(rho=27), @Meta.Sigma(rho=28), @Meta.Sigma(rho=32),
    @Meta.Sigma(rho=35)
  },
  exprs={@Meta.Expr()}
)
final public class MainActivity extends froid.app.FregeActivity  {
  



final public static class TQuestion implements frege.runtime.Value, Lazy<TQuestion> {
  private TQuestion(final Lazy<String/*<Character>*/> arg$1, final Lazy<Boolean> arg$2) {
    mem$text = Thunk.<String/*<Character>*/>shared(arg$1);
    mem$answer = Thunk.<Boolean>shared(arg$2);
  }
  final public int constructor() {
    return 0;
  }
  final public static TQuestion mk(final Lazy<String/*<Character>*/> arg$1, final Lazy<Boolean> arg$2) {
    return new TQuestion(arg$1, arg$2);
  }
  final public Lazy<String/*<Character>*/> mem$text  ;
  final public Lazy<Boolean> mem$answer  ;
  final public TQuestion call() {
    return this;
  }
  final public boolean isShared() {
    return true;
  }
  final public Thunk<TQuestion> asThunk() {
    return null;
  }
  @SuppressWarnings("unchecked") final public TQuestion simsalabim() {
    return (TQuestion)this;
  }
  final public static TQuestion upd$text(final TQuestion arg$1, final Lazy<String/*<Character>*/> arg$2) {
    return TQuestion.mk(arg$2, arg$1.mem$answer);
  }
  final public static <α> boolean has$text(final Lazy<α> arg$1) {
    return true;
  }
  final public static String/*<Character>*/ text(final TQuestion arg$1) {
    final String/*<Character>*/ a1$7822 = arg$1.mem$text.call();
    return a1$7822;
  }
  final public static TQuestion upd$answer(final TQuestion arg$1, final Lazy<Boolean> arg$2) {
    return TQuestion.mk(arg$1.mem$text, arg$2);
  }
  final public static TQuestion chg$text(
    final TQuestion arg$1, final Func.U<String/*<Character>*/, String/*<Character>*/> arg$2
  ) {
    return TQuestion.mk(
              Thunk.<String/*<Character>*/>nested(
                    new Lazy.D<Lazy<String/*<Character>*/>>() {
                      public Lazy<String/*<Character>*/> call() {
                        return arg$2.apply(arg$1.mem$text);
                      }
                    }
                  ),
              arg$1.mem$answer
            );
  }
  final public static TQuestion chg$answer(final TQuestion arg$1, final Func.U<Boolean, Boolean> arg$2) {
    return TQuestion.mk(
              arg$1.mem$text,
              Thunk.<Boolean>nested(
                    new Lazy.D<Lazy<Boolean>>() {
                      public Lazy<Boolean> call() {
                        return arg$2.apply(arg$1.mem$answer);
                      }
                    }
                  )
            );
  }
  final public static boolean answer(final TQuestion arg$1) {
    final boolean a2$7811 = (boolean)arg$1.mem$answer.call();
    return a2$7811;
  }
  final public static <α> boolean has$answer(final Lazy<α> arg$1) {
    return true;
  }
}
final public static PreludeBase.TList<PreludeBase.TTuple2<String/*<Character>*/, String/*<Character>*/>> sequenceQuestions(
  final PreludeBase.TList<TQuestion> arg$1
) {
  final PreludeBase.TList<String/*<Character>*/> questionStrings$7836 = PreludeList.<String/*<Character>*/, TQuestion>map(
        new Func.U.D<TQuestion, String/*<Character>*/>() {
          public Lazy<String/*<Character>*/> apply(final Lazy<TQuestion> arg$8534) {
            final TQuestion x$7837 = arg$8534.call();
            return Thunk.<String/*<Character>*/>shared(
                      new Lazy.D<String/*<Character>*/>() {
                        public String/*<Character>*/ call() {
                          return TQuestion.text(x$7837);
                        }
                      }
                    );
          }
        },
        arg$1
      );
  return PreludeList.<String/*<Character>*/, String/*<Character>*/>zip(
            questionStrings$7836,
            PreludeList.IListMonoid_$lbrack$rbrack.<String/*<Character>*/>$plus$plus(
                  PreludeList.IListView_$lbrack$rbrack.<String/*<Character>*/>tail(questionStrings$7836),
                  PreludeBase.TList.DCons.<String/*<Character>*/>mk(
                        Thunk.<String/*<Character>*/>shared(
                              new Lazy.D<String/*<Character>*/>() {
                                public String/*<Character>*/ call() {
                                  return PreludeList.IListView_$lbrack$rbrack.<String/*<Character>*/>head(
                                            questionStrings$7836
                                          );
                                }
                              }
                            ),
                        PreludeBase.TList.DList.<String/*<Character>*/>mk()
                      )
                )
          );
}
final public static int requestCheatCode = 0;
final public static PreludeBase.TList<TQuestion> questions = PreludeBase.TList.DCons.<
  TQuestion
>mk(
      TQuestion.mk(
            Thunk.<String/*<Character>*/>lazy("The Pacific Ocean is larger than the Atlantic Ocean"), Thunk.<Boolean>lazy(true)
          ),
      PreludeBase.TList.DCons.<TQuestion>mk(
            TQuestion.mk(
                  Thunk.<String/*<Character>*/>lazy("The Suez Canal connects the Red Sea and the Indian Ocean"),
                  Thunk.<Boolean>lazy(false)
                ),
            PreludeBase.TList.DCons.<TQuestion>mk(
                  TQuestion.mk(
                        Thunk.<String/*<Character>*/>lazy("The source of the Nile river is in Egypt"),
                        Thunk.<Boolean>lazy(false)
                      ),
                  PreludeBase.TList.DCons.<TQuestion>mk(
                        TQuestion.mk(
                              Thunk.<String/*<Character>*/>lazy("The Amazon river is the longest river in the Americas"),
                              Thunk.<Boolean>lazy(true)
                            ),
                        PreludeBase.TList.DCons.<TQuestion>mk(
                              TQuestion.mk(
                                    Thunk.<String/*<Character>*/>lazy(
                                          "Lake Baikal is the world\'s oldest and deepest freshwater lake"
                                        ),
                                    Thunk.<Boolean>lazy(true)
                                  ),
                              PreludeBase.TList.DCons.<TQuestion>mk(
                                    TQuestion.mk(
                                          Thunk.<String/*<Character>*/>lazy("The capital of Zimbabwe is Bulawayo"),
                                          Thunk.<Boolean>lazy(false)
                                        ),
                                    PreludeBase.TList.DCons.<TQuestion>mk(
                                          TQuestion.mk(
                                                Thunk.<String/*<Character>*/>lazy("Ghana is Africa\'s fastest growing economy"),
                                                Thunk.<Boolean>lazy(true)
                                              ),
                                          PreludeBase.TList.DList.<TQuestion>mk()
                                        )
                                  )
                            )
                      )
                )
          )
    );
final public static String/*<Character>*/ previousQuestion(final String/*<Character>*/ arg$1) {
  return PreludeBase.<String/*<Character>*/, String/*<Character>*/>maybe(
            Thunk.<String/*<Character>*/>lazy(arg$1),
            new Func.U.D<String/*<Character>*/, String/*<Character>*/>() {
              public Lazy<String/*<Character>*/> apply(final Lazy<String/*<Character>*/> arg$8537) {
                final String/*<Character>*/ v2321$8277 = arg$8537.call();
                return Thunk.<String/*<Character>*/>lazy(v2321$8277);
              }
            },
            List.<String/*<Character>*/, String/*<Character>*/>lookup(
                  PreludeBase.IEq_String.it, Thunk.<String/*<Character>*/>lazy(arg$1),
                  MainActivity.sequenceQuestions(PreludeList.<TQuestion>reverse(MainActivity.questions))
                )
          ).call();
}
final public static String/*<Character>*/ nextQuestion(final String/*<Character>*/ arg$1) {
  return PreludeBase.<String/*<Character>*/, String/*<Character>*/>maybe(
            Thunk.<String/*<Character>*/>lazy(arg$1),
            new Func.U.D<String/*<Character>*/, String/*<Character>*/>() {
              public Lazy<String/*<Character>*/> apply(final Lazy<String/*<Character>*/> arg$8539) {
                final String/*<Character>*/ v2321$8393 = arg$8539.call();
                return Thunk.<String/*<Character>*/>lazy(v2321$8393);
              }
            },
            List.<String/*<Character>*/, String/*<Character>*/>lookup(
                  PreludeBase.IEq_String.it, Thunk.<String/*<Character>*/>lazy(arg$1),
                  MainActivity.sequenceQuestions(MainActivity.questions)
                )
          ).call();
}
final public static Func.U<RealWorld, Short> navigationHandler(
  final Lazy<android.content.Context> arg$1, final Lazy<android.widget.TextView> arg$2, final Lazy<Boolean> arg$3,
  final Lazy<android.view.View> arg$4
) {
  final Func.U<RealWorld, String/*<Character>*/> v2038$8399 = Func.<RealWorld, String/*<Character>*/>coerceU(
        PreludeMonad.<Func.U<RealWorld, ?>, CharSequence, String/*<Character>*/>liftM(
              PreludeMonad.IMonad_ST.<RealWorld>mk(),
              new Func.U.D<CharSequence, String/*<Character>*/>() {
                public Lazy<String/*<Character>*/> apply(final Lazy<CharSequence> arg$8541) {
                  final CharSequence cs$7863 = arg$8541.call();
                  return Thunk.<String/*<Character>*/>shared(
                            new Lazy.D<String/*<Character>*/>() {
                              public String/*<Character>*/ call() {
                                return cs$7863.toString();
                              }
                            }
                          );
                }
              },
              Thunk.<Kind.U<Func.U<RealWorld, ?>, CharSequence>>shared(
                    new Lazy.D<Kind.U<Func.U<RealWorld, ?>, CharSequence>>() {
                      public Kind.U<Func.U<RealWorld, ?>, CharSequence> call() {
                        return (Kind.U<Func.U<RealWorld, ?>, CharSequence>)Thunk.<Func.U<RealWorld, CharSequence>>shared(
                                  new Lazy.D<Func.U<RealWorld, CharSequence>>() {
                                    public Func.U<RealWorld, CharSequence> call() {
                                      return TextView.TTextView.getText(arg$2.call());
                                    }
                                  }
                                ).call();
                      }
                    }
                  )
            )
      );
  return new Func.U.D<RealWorld, Short>() {
        public Lazy<Short> apply(final Lazy<RealWorld> arg$8544) {
          final String/*<Character>*/ v2041$8402 = v2038$8399.apply(arg$8544).call();
          final Func.U<RealWorld, Short> v2042$8403 = (boolean)arg$3.call() == true ? TextView.TTextView.setText(
                    arg$2.call(), MainActivity.nextQuestion(v2041$8402)
                  ) : TextView.TTextView.setText(arg$2.call(), MainActivity.previousQuestion(v2041$8402));
          return Thunk.<Short>nested(
                    new Lazy.D<Lazy<Short>>() {
                      public Lazy<Short> call() {
                        return v2042$8403.apply(arg$8544);
                      }
                    }
                  );
        }
      };
}
final public static Func.U<RealWorld, Short> handler(
  final Lazy<android.content.Context> arg$1, final Lazy<android.widget.TextView> arg$2, final Lazy<Boolean> arg$3,
  final Lazy<android.view.View> arg$4
) {
  final Func.U<RealWorld, String/*<Character>*/> v2038$8421 = Func.<RealWorld, String/*<Character>*/>coerceU(
        PreludeMonad.<Func.U<RealWorld, ?>, CharSequence, String/*<Character>*/>liftM(
              PreludeMonad.IMonad_ST.<RealWorld>mk(),
              new Func.U.D<CharSequence, String/*<Character>*/>() {
                public Lazy<String/*<Character>*/> apply(final Lazy<CharSequence> arg$8547) {
                  final CharSequence cs$7842 = arg$8547.call();
                  return Thunk.<String/*<Character>*/>shared(
                            new Lazy.D<String/*<Character>*/>() {
                              public String/*<Character>*/ call() {
                                return cs$7842.toString();
                              }
                            }
                          );
                }
              },
              Thunk.<Kind.U<Func.U<RealWorld, ?>, CharSequence>>shared(
                    new Lazy.D<Kind.U<Func.U<RealWorld, ?>, CharSequence>>() {
                      public Kind.U<Func.U<RealWorld, ?>, CharSequence> call() {
                        return (Kind.U<Func.U<RealWorld, ?>, CharSequence>)Thunk.<Func.U<RealWorld, CharSequence>>shared(
                                  new Lazy.D<Func.U<RealWorld, CharSequence>>() {
                                    public Func.U<RealWorld, CharSequence> call() {
                                      return TextView.TTextView.getText(arg$2.call());
                                    }
                                  }
                                ).call();
                      }
                    }
                  )
            )
      );
  return new Func.U.D<RealWorld, Short>() {
        public Lazy<Short> apply(final Lazy<RealWorld> arg$8550) {
          final String/*<Character>*/ v2041$8424 = v2038$8421.apply(arg$8550).call();
          final Func.U<RealWorld, android.widget.Toast> v2038$8443 = Toast.TToast.makeText(
                arg$1.call(),
                (boolean)PreludeBase.<Boolean, Boolean>maybe(
                      Thunk.<Boolean>lazy(false),
                      new Func.U.D<Boolean, Boolean>() {
                        public Lazy<Boolean> apply(final Lazy<Boolean> arg$8552) {
                          final boolean v2321$8461 = (boolean)arg$8552.call();
                          return Thunk.<Boolean>lazy(v2321$8461);
                        }
                      },
                      Maybe.IFunctor_Maybe.<TQuestion, Boolean>fmap(
                            new Func.U.D<TQuestion, Boolean>() {
                              public Lazy<Boolean> apply(final Lazy<TQuestion> arg$8554) {
                                final TQuestion x$7845 = arg$8554.call();
                                return Thunk.<Boolean>shared(
                                          new Lazy.D<Boolean>() {
                                            public Boolean call() {
                                              return TQuestion.answer(x$7845);
                                            }
                                          }
                                        );
                              }
                            },
                            List.<TQuestion>find(
                                  new Func.U.D<TQuestion, Boolean>() {
                                    public Lazy<Boolean> apply(final Lazy<TQuestion> arg$8556) {
                                      final TQuestion x$7846 = arg$8556.call();
                                      return Thunk.<Boolean>shared(
                                                new Lazy.D<Boolean>() {
                                                  public Boolean call() {
                                                    return TQuestion.text(x$7846).equals(
                                                              v2041$8424
                                                            );
                                                  }
                                                }
                                              );
                                    }
                                  },
                                  MainActivity.questions
                                )
                          )
                    ).call() == (boolean)arg$3.call() ? "You got it right!" : "Wrong!",
                android.widget.Toast.LENGTH_SHORT
              );
          final android.widget.Toast v2041$8446 = v2038$8443.apply(arg$8550).call();
          final Func.U<RealWorld, Short> v4801$8470 = Toast.TToast.show(v2041$8446);
          final short v4804$8472 = (short)v4801$8470.apply(arg$8550).call();
          final Func.U<RealWorld, Short> v4805$8473 = Thunk.<Func.U<RealWorld, Short>>shared(
                new Lazy.D<Func.U<RealWorld, Short>>() {
                  public Func.U<RealWorld, Short> call() {
                    return TextView.TTextView.setText(arg$2.call(), MainActivity.nextQuestion(v2041$8424));
                  }
                }
              ).call();
          return Thunk.<Short>nested(
                    new Lazy.D<Lazy<Short>>() {
                      public Lazy<Short> call() {
                        return v4805$8473.apply(arg$8550);
                      }
                    }
                  );
        }
      };
}
final public static Func.U<RealWorld, Short> cheatHandler(
  final Lazy<froid.app.FregeActivity> arg$1, final Lazy<android.content.Context> arg$2,
  final Lazy<android.widget.TextView> arg$3, final Lazy<android.view.View> arg$4
) {
  final Func.U<RealWorld, String/*<Character>*/> v2038$8491 = Func.<RealWorld, String/*<Character>*/>coerceU(
        PreludeMonad.<Func.U<RealWorld, ?>, CharSequence, String/*<Character>*/>liftM(
              PreludeMonad.IMonad_ST.<RealWorld>mk(),
              new Func.U.D<CharSequence, String/*<Character>*/>() {
                public Lazy<String/*<Character>*/> apply(final Lazy<CharSequence> arg$8563) {
                  final CharSequence cs$7853 = arg$8563.call();
                  return Thunk.<String/*<Character>*/>shared(
                            new Lazy.D<String/*<Character>*/>() {
                              public String/*<Character>*/ call() {
                                return cs$7853.toString();
                              }
                            }
                          );
                }
              },
              Thunk.<Kind.U<Func.U<RealWorld, ?>, CharSequence>>shared(
                    new Lazy.D<Kind.U<Func.U<RealWorld, ?>, CharSequence>>() {
                      public Kind.U<Func.U<RealWorld, ?>, CharSequence> call() {
                        return (Kind.U<Func.U<RealWorld, ?>, CharSequence>)Thunk.<Func.U<RealWorld, CharSequence>>shared(
                                  new Lazy.D<Func.U<RealWorld, CharSequence>>() {
                                    public Func.U<RealWorld, CharSequence> call() {
                                      return TextView.TTextView.getText(arg$3.call());
                                    }
                                  }
                                ).call();
                      }
                    }
                  )
            )
      );
  return new Func.U.D<RealWorld, Short>() {
        public Lazy<Short> apply(final Lazy<RealWorld> arg$8566) {
          final String/*<Character>*/ v2041$8494 = v2038$8491.apply(arg$8566).call();
          final Func.U<RealWorld, android.content.Intent> v2038$8513 = CheatActivity.newIntent(
                arg$2.call(),
                Thunk.<Boolean>nested(
                      new Lazy.D<Lazy<Boolean>>() {
                        public Lazy<Boolean> call() {
                          return PreludeBase.<Boolean, Boolean>maybe(
                                    Thunk.<Boolean>lazy(false),
                                    new Func.U.D<Boolean, Boolean>() {
                                      public Lazy<Boolean> apply(final Lazy<Boolean> arg$8568) {
                                        final boolean v2321$8531 = (boolean)arg$8568.call();
                                        return Thunk.<Boolean>lazy(v2321$8531);
                                      }
                                    },
                                    Maybe.IFunctor_Maybe.<TQuestion, Boolean>fmap(
                                          new Func.U.D<TQuestion, Boolean>() {
                                            public Lazy<Boolean> apply(final Lazy<TQuestion> arg$8570) {
                                              final TQuestion x$7856 = arg$8570.call();
                                              return Thunk.<Boolean>shared(
                                                        new Lazy.D<Boolean>() {
                                                          public Boolean call() {
                                                            return TQuestion.answer(x$7856);
                                                          }
                                                        }
                                                      );
                                            }
                                          },
                                          List.<TQuestion>find(
                                                new Func.U.D<TQuestion, Boolean>() {
                                                  public Lazy<Boolean> apply(final Lazy<TQuestion> arg$8572) {
                                                    final TQuestion x$7857 = arg$8572
                                                    .call();
                                                    return Thunk.<Boolean>shared(
                                                              new Lazy.D<Boolean>() {
                                                                public Boolean call() {
                                                                  return TQuestion.text(
                                                                            x$7857
                                                                          ).equals(v2041$8494);
                                                                }
                                                              }
                                                            );
                                                  }
                                                },
                                                MainActivity.questions
                                              )
                                        )
                                  );
                        }
                      }
                    )
              );
          final android.content.Intent v2041$8516 = v2038$8513.apply(arg$8566).call();
          final Func.U<RealWorld, Short> v2042$8517 = Activity.TActivity.startActivityForResult(
                arg$1.call(), v2041$8516, MainActivity.requestCheatCode
              );
          return Thunk.<Short>nested(
                    new Lazy.D<Lazy<Short>>() {
                      public Lazy<Short> call() {
                        return v2042$8517.apply(arg$8566);
                      }
                    }
                  );
        }
      };
}
final public static Func.U<RealWorld, Short> onCreate(final froid.app.FregeActivity arg$1) {
  final Func.U<RealWorld, android.content.Context> v2038$8283 = Activity.TActivity.getApplicationContext(
        arg$1
      );
  return new Func.U.D<RealWorld, Short>() {
        public Lazy<Short> apply(final Lazy<RealWorld> arg$8578) {
          final android.content.Context v2041$8286 = v2038$8283.apply(arg$8578).call();
          final Func.U<RealWorld, android.widget.TextView> v2038$8329 = TextView.asTextView(
                arg$1, io.github.mchav.freoquiz.R.id.question_text
              );
          final Func.U<RealWorld, Short> v4801$8308 = Activity.TActivity.setContentView(
                arg$1, io.github.mchav.freoquiz.R.layout.activity_main
              );
          final short v4804$8310 = (short)v4801$8308.apply(arg$8578).call();
          final Func.U<RealWorld, Short> v4805$8311 = (new Func.U.D<RealWorld, Short>() {
            public Lazy<Short> apply(final Lazy<RealWorld> arg$8581) {
              final android.widget.TextView v2041$8332 = v2038$8329.apply(arg$8581).call();
              final Func.U<RealWorld, PreludeBase.TList<android.view.View>> v2038$8351 =
              Func.<RealWorld, PreludeBase.TList<android.view.View>>coerceU(
                    PreludeMonad.<Func.U<RealWorld, ?>, android.view.View, Integer>mapM(
                          PreludeMonad.IMonad_ST.<RealWorld>mk(), PreludeMonad.IMonad_ST.<RealWorld>mk(),
                          new Func.U.D<Integer, Kind.U<Func.U<RealWorld, ?>, android.view.View>>() {
                            public Lazy<Kind.U<Func.U<RealWorld, ?>, android.view.View>> apply(
                              final Lazy<Integer> η$8583
                            ) {
                              return Thunk.<Kind.U<Func.U<RealWorld, ?>, android.view.View>>shared(
                                        new Lazy.D<Kind.U<Func.U<RealWorld, ?>, android.view.View>>() {
                                          public Kind.U<Func.U<RealWorld, ?>, android.view.View> call() {
                                            return (Kind.U<Func.U<RealWorld, ?>, android.view.View>)Thunk.<
                                                  Func.U<RealWorld, android.view.View>
                                                >shared(
                                                      new Lazy.D<Func.U<RealWorld, android.view.View>>() {
                                                        public Func.U<RealWorld, android.view.View> call() {
                                                          return Activity.TActivity.findViewById(
                                                                    arg$1, (int)η$8583.call()
                                                                  );
                                                        }
                                                      }
                                                    ).call();
                                          }
                                        }
                                      );
                            }
                          },
                          PreludeBase.TList.DCons.<Integer>mk(
                                Thunk.<Integer>lazy(io.github.mchav.freoquiz.R.id.btnFalse),
                                PreludeBase.TList.DCons.<Integer>mk(
                                      Thunk.<Integer>lazy(io.github.mchav.freoquiz.R.id.btnTrue),
                                      PreludeBase.TList.DCons.<Integer>mk(
                                            Thunk.<Integer>lazy(io.github.mchav.freoquiz.R.id.btnNext),
                                            PreludeBase.TList.DCons.<Integer>mk(
                                                  Thunk.<Integer>lazy(io.github.mchav.freoquiz.R.id.btnPrev),
                                                  PreludeBase.TList.DCons.<Integer>mk(
                                                        Thunk.<Integer>lazy(io.github.mchav.freoquiz.R.id.btnCheat),
                                                        PreludeBase.TList.DList.<Integer>mk()
                                                      )
                                                )
                                          )
                                    )
                              )
                        )
                  );
              final PreludeBase.TList<android.view.View> v2041$8354 = v2038$8351.apply(
                    arg$8581
                  ).call();
              final Func.U<RealWorld, PreludeBase.TList<Short>> v4801$8376 = Func.<RealWorld, PreludeBase.TList<Short>>coerceU(
                    PreludeMonad.<
                      Func.U<RealWorld, ?>, Short, android.view.View, Func.U<android.view.View, Func.U<RealWorld, Short>>
                    >zipWithM(
                          PreludeMonad.IMonad_ST.<RealWorld>mk(), PreludeMonad.IMonad_ST.<RealWorld>mk(),
                          new Func.U.D<
                            android.view.View,
                            Func.U<Func.U<android.view.View, Func.U<RealWorld, Short>>, Kind.U<Func.U<RealWorld, ?>, Short>>
                          >() {
                            public Lazy<Func.U<
                              Func.U<android.view.View, Func.U<RealWorld, Short>>, Kind.U<Func.U<RealWorld, ?>, Short>
                            >> apply(final Lazy<android.view.View> η$8586) {
                              return new Func.U.D<
                                    Func.U<android.view.View, Func.U<RealWorld, Short>>, Kind.U<Func.U<RealWorld, ?>, Short>
                                  >() {
                                    public Lazy<Kind.U<Func.U<RealWorld, ?>, Short>> apply(
                                      final Lazy<Func.U<android.view.View, Func.U<RealWorld, Short>>> η$8587
                                    ) {
                                      return Thunk.<Kind.U<Func.U<RealWorld, ?>, Short>>shared(
                                                new Lazy.D<Kind.U<Func.U<RealWorld, ?>, Short>>() {
                                                  public Kind.U<Func.U<RealWorld, ?>, Short> call() {
                                                    return (Kind.U<Func.U<RealWorld, ?>, Short>)Thunk.<
                                                          Func.U<RealWorld, Short>
                                                        >shared(
                                                              new Lazy.D<Func.U<RealWorld, Short>>() {
                                                                public Func.U<RealWorld, Short> call() {
                                                                  return View.setOnClick(
                                                                            η$8586.call(), η$8587.call()
                                                                          );
                                                                }
                                                              }
                                                            ).call();
                                                  }
                                                }
                                              );
                                    }
                                  };
                            }
                          },
                          v2041$8354,
                          PreludeBase.TList.DCons.<Func.U<android.view.View, Func.U<RealWorld, Short>>>mk(
                                new Func.U.D<android.view.View, Func.U<RealWorld, Short>>() {
                                  public Lazy<Func.U<RealWorld, Short>> apply(final Lazy<android.view.View> η$8588) {
                                    return Thunk.<Func.U<RealWorld, Short>>shared(
                                              new Lazy.D<Func.U<RealWorld, Short>>() {
                                                public Func.U<RealWorld, Short> call() {
                                                  return MainActivity.handler(
                                                            Thunk.<android.content.Context>lazy(
                                                                  v2041$8286
                                                                ),
                                                            Thunk.<android.widget.TextView>lazy(
                                                                  v2041$8332
                                                                ),
                                                            Thunk.<Boolean>lazy(false), η$8588
                                                          );
                                                }
                                              }
                                            );
                                  }
                                },
                                PreludeBase.TList.DCons.<Func.U<android.view.View, Func.U<RealWorld, Short>>>mk(
                                      new Func.U.D<android.view.View, Func.U<RealWorld, Short>>() {
                                        public Lazy<Func.U<RealWorld, Short>> apply(final Lazy<android.view.View> η$8589) {
                                          return Thunk.<Func.U<RealWorld, Short>>shared(
                                                    new Lazy.D<Func.U<RealWorld, Short>>() {
                                                      public Func.U<RealWorld, Short> call() {
                                                        return MainActivity.handler(
                                                                  Thunk.<android.content.Context>lazy(
                                                                        v2041$8286
                                                                      ),
                                                                  Thunk.<android.widget.TextView>lazy(
                                                                        v2041$8332
                                                                      ),
                                                                  Thunk.<Boolean>lazy(true), η$8589
                                                                );
                                                      }
                                                    }
                                                  );
                                        }
                                      },
                                      PreludeBase.TList.DCons.<Func.U<android.view.View, Func.U<RealWorld, Short>>>mk(
                                            new Func.U.D<android.view.View, Func.U<RealWorld, Short>>() {
                                              public Lazy<Func.U<RealWorld, Short>> apply(
                                                final Lazy<android.view.View> η$8590
                                              ) {
                                                return Thunk.<Func.U<RealWorld, Short>>shared(
                                                          new Lazy.D<Func.U<RealWorld, Short>>() {
                                                            public Func.U<RealWorld, Short> call() {
                                                              return MainActivity.navigationHandler(
                                                                        Thunk.<android.content.Context>lazy(
                                                                              v2041$8286
                                                                            ),
                                                                        Thunk.<android.widget.TextView>lazy(
                                                                              v2041$8332
                                                                            ),
                                                                        Thunk.<Boolean>lazy(true), η$8590
                                                                      );
                                                            }
                                                          }
                                                        );
                                              }
                                            },
                                            PreludeBase.TList.DCons.<Func.U<android.view.View, Func.U<RealWorld, Short>>>mk(
                                                  new Func.U.D<android.view.View, Func.U<RealWorld, Short>>() {
                                                    public Lazy<Func.U<RealWorld, Short>> apply(
                                                      final Lazy<android.view.View> η$8591
                                                    ) {
                                                      return Thunk.<Func.U<RealWorld, Short>>shared(
                                                                new Lazy.D<Func.U<RealWorld, Short>>() {
                                                                  public Func.U<RealWorld, Short> call() {
                                                                    return MainActivity.navigationHandler(
                                                                              Thunk.<android.content.Context>lazy(
                                                                                    v2041$8286
                                                                                  ),
                                                                              Thunk.<android.widget.TextView>lazy(
                                                                                    v2041$8332
                                                                                  ),
                                                                              Thunk.<Boolean>lazy(false), η$8591
                                                                            );
                                                                  }
                                                                }
                                                              );
                                                    }
                                                  },
                                                  PreludeBase.TList.DCons.<
                                                    Func.U<android.view.View, Func.U<RealWorld, Short>>
                                                  >mk(
                                                        new Func.U.D<android.view.View, Func.U<RealWorld, Short>>() {
                                                          public Lazy<Func.U<RealWorld, Short>> apply(
                                                            final Lazy<android.view.View> η$8592
                                                          ) {
                                                            return Thunk.<Func.U<RealWorld, Short>>shared(
                                                                      new Lazy.D<Func.U<
                                                                        RealWorld, Short
                                                                      >>() {
                                                                        public Func.U<
                                                                          RealWorld, Short
                                                                        > call() {
                                                                          return MainActivity.cheatHandler(
                                                                                    Thunk.<
                                                                                      froid.app.FregeActivity
                                                                                    >lazy(
                                                                                          arg$1
                                                                                        ),
                                                                                    Thunk.<
                                                                                      android.content.Context
                                                                                    >lazy(
                                                                                          v2041$8286
                                                                                        ),
                                                                                    Thunk.<
                                                                                      android.widget.TextView
                                                                                    >lazy(
                                                                                          v2041$8332
                                                                                        ),
                                                                                    η$8592
                                                                                  );
                                                                        }
                                                                      }
                                                                    );
                                                          }
                                                        },
                                                        PreludeBase.TList.DList.<
                                                          Func.U<android.view.View, Func.U<RealWorld, Short>>
                                                        >mk()
                                                      )
                                                )
                                          )
                                    )
                              )
                        )
                  );
              final PreludeBase.TList<Short> v4804$8378 = v4801$8376.apply(arg$8581).call();
              final Func.U<RealWorld, Short> v4805$8379 = Thunk.<Func.U<RealWorld, Short>>shared(
                    new Lazy.D<Func.U<RealWorld, Short>>() {
                      public Func.U<RealWorld, Short> call() {
                        return TextView.TTextView.setText(
                                  v2041$8332,
                                  TQuestion.text(PreludeList.IListView_$lbrack$rbrack.<TQuestion>head(MainActivity.questions))
                                );
                      }
                    }
                  ).call();
              return Thunk.<Short>nested(
                        new Lazy.D<Lazy<Short>>() {
                          public Lazy<Short> call() {
                            return v4805$8379.apply(arg$8581);
                          }
                        }
                      );
            }
          }).call();
          return Thunk.<Short>nested(
                    new Lazy.D<Lazy<Short>>() {
                      public Lazy<Short> call() {
                        return v4805$8311.apply(arg$8578);
                      }
                    }
                  );
        }
      };
}

}
