/*
  Source code is in UTF-8 encoding. The following symbols may appear, among others:
  α β γ δ ε ζ η θ ι κ λ μ ν ξ ο π ρ ς σ τ υ φ χ ψ ω « • ¦ » ∀ ∃ ∷ … → ← ﬁ ﬂ ƒ
  If you can't read this, you're out of luck. This code was generated with the frege compiler version 3.24.100
  from src/main/frege/io/github/mchav/freoquiz/Types.fr Do not edit this file!
  Instead, edit the source file and recompile.
*/

package io.github.mchav.freoquiz;

import frege.run7.Func;
import frege.run7.Lazy;
import frege.run7.Thunk;
import frege.run.Kind;
import frege.run.RunTM;
import frege.runtime.Meta;
import frege.runtime.Phantom.RealWorld;
import frege.Prelude;
import frege.control.Category;
import frege.control.Semigroupoid;
import frege.java.IO;
import frege.java.Lang;
import frege.java.Util;
import frege.java.util.Regex;
import frege.prelude.Maybe;
import frege.prelude.PreludeArrays;
import frege.prelude.PreludeBase;
import frege.prelude.PreludeIO;
import frege.prelude.PreludeList;
import frege.prelude.PreludeMonad;
import frege.prelude.PreludeText;

@SuppressWarnings("unused")
@Meta.FregePackage(
  source="src\\main\\frege\\io\\github\\mchav\\freoquiz\\Types.fr", time=1482276213719L, jmajor=1,
  jminor=7,
  imps={
    "frege.Prelude", "frege.prelude.PreludeArrays", "frege.prelude.PreludeBase", "frege.prelude.PreludeIO",
    "frege.prelude.PreludeList", "frege.prelude.PreludeMonad", "frege.prelude.PreludeText", "frege.java.util.Regex"
  },
  nmss={"Prelude", "PreludeArrays", "PreludeBase", "PreludeIO", "PreludeList", "PreludeMonad", "PreludeText", "Regexp"},
  symas={},
  symcs={
    @Meta.SymC(
      offset=4029, name=@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="CastTarget"), tau=1,
      ins1={
        @Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="Toolbar"),
        @Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="Button"),
        @Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="TextView")
      },
      ins2={
        @Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="CastTarget_Toolbar"),
        @Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="CastTarget_Button"),
        @Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="CastTarget_TextView")
      },
      lnks={},
      funs={
        @Meta.SymV(
          offset=4053,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="CastTarget", member="downcast"),
          stri="s(u)", sig=1, abst=true, depth=1, rkind=33, publik=false
        )
      }
    )
  },
  symis={
    @Meta.SymI(
      offset=4124, name=@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="CastTarget_TextView"),
      clas=@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="CastTarget"), typ=2,
      lnks={},
      funs={
        @Meta.SymV(
          offset=4171,
          name=@Meta.QName(
            kind=2, pack="io.github.mchav.freoquiz.Types", base="CastTarget_TextView", member="downcast"
          ),
          stri="s(s)", sig=3, nativ="(android.widget.TextView)", depth=1, rkind=33
        )
      }
    ),
    @Meta.SymI(
      offset=4277, name=@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="CastTarget_Button"),
      clas=@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="CastTarget"), typ=4,
      lnks={},
      funs={
        @Meta.SymV(
          offset=4322,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="CastTarget_Button", member="downcast"),
          stri="s(s)", sig=5, nativ="(android.widget.Button)", depth=1, rkind=33
        )
      }
    ),
    @Meta.SymI(
      offset=3433, name=@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="CastTarget_Toolbar"),
      clas=@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="CastTarget"), typ=6,
      lnks={},
      funs={
        @Meta.SymV(
          offset=3479,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="CastTarget_Toolbar", member="downcast"),
          stri="s(s)", sig=7, nativ="(android.widget.Toolbar)", depth=1, rkind=33
        )
      }
    )
  },
  symts={
    @Meta.SymT(
      offset=1734, name=@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="View"), typ=8,
      kind=0, cons={}, lnks={},
      funs={
        @Meta.SymV(
          offset=1995,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="View", member="setVisibility"),
          stri="s(ss)", sig=10, nativ="setVisibility", depth=2, rkind=33
        ),
        @Meta.SymV(
          offset=1789, name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="View", member="visible"),
          stri="s", sig=9, nativ="android.view.View.VISIBLE", pur=true, depth=0, rkind=33
        ),
        @Meta.SymV(
          offset=1849, name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="View", member="invisible"),
          stri="s", sig=9, nativ="android.view.View.INVISIBLE", pur=true, depth=0, rkind=33
        ),
        @Meta.SymV(
          offset=1908,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="View", member="setOnClickListener"),
          stri="s(ss)", sig=12, nativ="setOnClickListener", depth=2, rkind=33
        )
      },
      nativ="android.view.View"
    ),
    @Meta.SymT(
      offset=4429, name=@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="Toast"), typ=13,
      kind=0, cons={}, lnks={},
      funs={
        @Meta.SymV(
          offset=4730, name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="Toast", member="show"),
          stri="s(s)", sig=15, nativ="show", depth=1, rkind=33
        ),
        @Meta.SymV(
          offset=4615, name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="Toast", member="makeText"),
          stri="s(sss)", sig=18, nativ="android.widget.Toast.makeText", depth=3, rkind=33
        ),
        @Meta.SymV(
          offset=4483,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="Toast", member="lengthLong"), stri="s",
          sig=9, nativ="android.widget.Toast.LENGTH_LONG", depth=0, rkind=33
        ),
        @Meta.SymV(
          offset=4548,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="Toast", member="lengthShort"), stri="s",
          sig=9, nativ="android.widget.Toast.LENGTH_SHORT", depth=0, rkind=33
        )
      },
      nativ="android.widget.Toast"
    ),
    @Meta.SymT(
      offset=3061, name=@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="Toolbar"), typ=6,
      kind=0, cons={},
      lnks={
        @Meta.SymL(
          offset=3479,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="Toolbar", member="downcast"),
          alias=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="CastTarget_Toolbar", member="downcast")
        )
      },
      funs={}, nativ="android.widget.Toolbar"
    ),
    @Meta.SymT(
      offset=3664, name=@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="TextView"), typ=2,
      kind=0, cons={},
      lnks={
        @Meta.SymL(
          offset=4171,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="TextView", member="downcast"),
          alias=@Meta.QName(
            kind=2, pack="io.github.mchav.freoquiz.Types", base="CastTarget_TextView", member="downcast"
          )
        )
      },
      funs={
        @Meta.SymV(
          offset=3903,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="TextView", member="setVisibility"),
          stri="s(ss)", sig=20, nativ="setVisibility", depth=2, rkind=33
        ),
        @Meta.SymV(
          offset=3787,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="TextView", member="setText"),
          stri="s(ss)", sig=21, nativ="setText", depth=2, rkind=33
        ),
        @Meta.SymV(
          offset=3845,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="TextView", member="getText"),
          stri="s(s)", sig=22, nativ="getText", depth=1, rkind=33
        ),
        @Meta.SymV(
          offset=3721, name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="TextView", member="new"),
          stri="s(s)", sig=23, nativ="new", depth=1, rkind=33
        )
      },
      nativ="android.widget.TextView"
    ),
    @Meta.SymT(
      offset=1369, name=@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="Question"), typ=24,
      kind=0,
      cons={
        @Meta.SymD(
          offset=1380,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="Question", member="Question"), cid=0,
          typ=26,
          fields={
            @Meta.Field(name="text", offset=1391, sigma=17, strict=false),
            @Meta.Field(name="answer", offset=1407, sigma=25, strict=false)
          }
        )
      },
      lnks={},
      funs={
        @Meta.SymV(
          offset=1392,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="Question", member="upd$text"),
          stri="s(su)", sig=27, depth=2, rkind=49, doc="update field @text@"
        ),
        @Meta.SymV(
          offset=1392,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="Question", member="has$text"),
          stri="s(u)", sig=29, depth=1, rkind=49, doc="check if constructor has field @text@"
        ),
        @Meta.SymV(
          offset=1392, name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="Question", member="text"),
          stri="s(s)", sig=30, depth=1, rkind=49, doc="access field @text@"
        ),
        @Meta.SymV(
          offset=1408,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="Question", member="upd$answer"),
          stri="s(su)", sig=31, depth=2, rkind=49, doc="update field @answer@"
        ),
        @Meta.SymV(
          offset=1392,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="Question", member="chg$text"),
          stri="s(ss)", sig=33, depth=2, rkind=49, doc="change field @text@"
        ),
        @Meta.SymV(
          offset=1408,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="Question", member="chg$answer"),
          stri="s(ss)", sig=35, depth=2, rkind=49, doc="change field @answer@"
        ),
        @Meta.SymV(
          offset=1408,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="Question", member="answer"),
          stri="s(s)", sig=36, depth=1, rkind=49, doc="access field @answer@"
        ),
        @Meta.SymV(
          offset=1408,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="Question", member="has$answer"),
          stri="s(u)", sig=29, depth=1, rkind=49, doc="check if constructor has field @answer@"
        )
      },
      prod=true
    ),
    @Meta.SymT(
      offset=3109, name=@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="OnClickListener"), typ=37,
      kind=0, cons={}, lnks={}, funs={}, nativ="android.view.View.OnClickListener"
    ),
    @Meta.SymT(
      offset=1644, name=@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="MenuItem"), typ=38,
      kind=0, cons={}, lnks={}, funs={}, nativ="android.view.MenuItem"
    ),
    @Meta.SymT(
      offset=1604, name=@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="Menu"), typ=39,
      kind=0, cons={}, lnks={}, funs={}, nativ="android.view.Menu"
    ),
    @Meta.SymT(
      offset=2100, name=@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="Intent"), typ=40,
      kind=0, cons={}, lnks={},
      funs={
        @Meta.SymV(
          offset=2364,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="Intent", member="putExtra"),
          stri="s(sss)", sig=42, nativ="putExtra", depth=3, rkind=33
        ),
        @Meta.SymV(
          offset=2157, name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="Intent", member="newα"),
          stri="s(s)", sig=44, nativ="new", depth=1, rkind=33, publik=false
        ),
        @Meta.SymV(
          offset=2157, name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="Intent", member="newβ"),
          stri="s(ss)", sig=46, nativ="new", depth=2, rkind=33, publik=false
        ),
        @Meta.SymV(
          offset=2287,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="Intent", member="getBooleanExtra"),
          stri="s(sss)", sig=47, nativ="getBooleanExtra", depth=3, rkind=33
        ),
        @Meta.SymV(
          offset=2157, name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="Intent", member="new"),
          stri="s", sig=48, nativ="new", depth=0, rkind=33,
          over={
            @Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="Intent", member="newα"),
            @Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="Intent", member="newβ")
          }
        )
      },
      nativ="android.content.Intent"
    ),
    @Meta.SymT(
      offset=2051, name=@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="Context"), typ=49,
      kind=0, cons={}, lnks={}, funs={}, nativ="android.content.Context"
    ),
    @Meta.SymT(
      offset=3963, name=@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="ClassCastException"), typ=50,
      kind=0, cons={}, lnks={}, funs={}, nativ="java.lang.ClassCastException"
    ),
    @Meta.SymT(
      offset=3176, name=@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="Button"), typ=4,
      kind=0, cons={},
      lnks={
        @Meta.SymL(
          offset=4322,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="Button", member="downcast"),
          alias=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="CastTarget_Button", member="downcast")
        )
      },
      funs={
        @Meta.SymV(
          offset=3321,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="Button", member="setVisibility"),
          stri="s(ss)", sig=52, nativ="setVisibility", depth=2, rkind=33
        ),
        @Meta.SymV(
          offset=3383, name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="Button", member="getText"),
          stri="s(s)", sig=53, nativ="getText", depth=1, rkind=33
        ),
        @Meta.SymV(
          offset=3232,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="Button", member="setOnClickListener"),
          stri="s(ss)", sig=54, nativ="setOnClickListener", depth=2, rkind=33
        )
      },
      nativ="android.widget.Button"
    ),
    @Meta.SymT(
      offset=1692, name=@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="Bundle"), typ=55,
      kind=0, cons={}, lnks={}, funs={}, nativ="android.os.Bundle"
    ),
    @Meta.SymT(
      offset=3588, name=@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="AppCompatActivity"), typ=56,
      kind=0, cons={}, lnks={}, funs={}, nativ="android.support.v7.app.AppCompatActivity"
    ),
    @Meta.SymT(
      offset=2428, name=@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="Activity"), typ=57,
      kind=0, cons={}, lnks={},
      funs={
        @Meta.SymV(
          offset=2972,
          name=@Meta.QName(
            kind=2, pack="io.github.mchav.freoquiz.Types", base="Activity", member="startActivityForResult"
          ),
          stri="s(sss)", sig=59, nativ="startActivityForResult", depth=3, rkind=33
        ),
        @Meta.SymV(
          offset=2759,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="Activity", member="setContentView"),
          stri="s(ss)", sig=60, nativ="setContentView", depth=2, rkind=33
        ),
        @Meta.SymV(
          offset=2895,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="Activity", member="setResult"),
          stri="s(sss)", sig=61, nativ="setResult", depth=3, rkind=33
        ),
        @Meta.SymV(
          offset=2561,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="Activity", member="resultOk"), stri="s",
          sig=9, nativ="android.app.Activity.RESULT_OK", depth=0, rkind=33
        ),
        @Meta.SymV(
          offset=2821,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="Activity", member="setActionBar"),
          stri="s(ss)", sig=63, nativ="setActionBar", depth=2, rkind=33
        ),
        @Meta.SymV(
          offset=2685,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="Activity", member="findViewById"),
          stri="s(ss)", sig=64, nativ="findViewById", depth=2, rkind=33
        ),
        @Meta.SymV(
          offset=2482,
          name=@Meta.QName(
            kind=2, pack="io.github.mchav.freoquiz.Types", base="Activity", member="getApplicationContext"
          ),
          stri="s(s)", sig=65, nativ="getApplicationContext", depth=1, rkind=33
        ),
        @Meta.SymV(
          offset=2619,
          name=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="Activity", member="getIntent"),
          stri="s(s)", sig=66, nativ="getIntent", depth=1, rkind=33
        )
      },
      nativ="android.app.Activity"
    )
  },
  symvs={
    @Meta.SymV(
      offset=394, name=@Meta.QName(pack="io.github.mchav.freoquiz.Types", base="toolbarId"), stri="s",
      sig=9, nativ="io.github.mchav.freoquiz.R.id.toolbar", pur=true, depth=0, rkind=33
    ),
    @Meta.SymV(
      offset=686, name=@Meta.QName(pack="io.github.mchav.freoquiz.Types", base="showAnswerButtonId"), stri="s",
      sig=9, nativ="io.github.mchav.freoquiz.R.id.showAnswerButton", pur=true, depth=0, rkind=33
    ),
    @Meta.SymV(
      offset=231, name=@Meta.QName(pack="io.github.mchav.freoquiz.Types", base="questionText"), stri="s",
      sig=9, nativ="io.github.mchav.freoquiz.R.id.question_text", pur=true, depth=0, rkind=33
    ),
    @Meta.SymV(
      offset=1555, name=@Meta.QName(pack="io.github.mchav.freoquiz.Types", base="packageName"), stri="s",
      sig=17, depth=0, rkind=49
    ),
    @Meta.SymV(
      offset=1433, name=@Meta.QName(pack="io.github.mchav.freoquiz.Types", base="onClick"), stri="s(s)",
      sig=68, nativ="io.github.mchav.freoquiz.Types.onClickHandler", depth=1, rkind=33
    ),
    @Meta.SymV(
      offset=849, name=@Meta.QName(pack="io.github.mchav.freoquiz.Types", base="btnPrevId"), stri="s",
      sig=9, nativ="io.github.mchav.freoquiz.R.id.btnPrev", pur=true, depth=0, rkind=33
    ),
    @Meta.SymV(
      offset=777, name=@Meta.QName(pack="io.github.mchav.freoquiz.Types", base="btnNextId"), stri="s",
      sig=9, nativ="io.github.mchav.freoquiz.R.id.btnNext", pur=true, depth=0, rkind=33
    ),
    @Meta.SymV(
      offset=612, name=@Meta.QName(pack="io.github.mchav.freoquiz.Types", base="btnCheatId"), stri="s",
      sig=9, nativ="io.github.mchav.freoquiz.R.id.btnCheat", pur=true, depth=0, rkind=33
    ),
    @Meta.SymV(
      offset=466, name=@Meta.QName(pack="io.github.mchav.freoquiz.Types", base="btnFalseId"), stri="s",
      sig=9, nativ="io.github.mchav.freoquiz.R.id.btnFalse", pur=true, depth=0, rkind=33
    ),
    @Meta.SymV(
      offset=540, name=@Meta.QName(pack="io.github.mchav.freoquiz.Types", base="btnTrueId"), stri="s",
      sig=9, nativ="io.github.mchav.freoquiz.R.id.btnTrue", pur=true, depth=0, rkind=33
    ),
    @Meta.SymV(
      offset=5206, name=@Meta.QName(pack="io.github.mchav.freoquiz.Types", base="attachHandler"), stri="s(us)",
      sig=69, depth=2, rkind=49
    ),
    @Meta.SymV(
      offset=4990, name=@Meta.QName(pack="io.github.mchav.freoquiz.Types", base="asButton"), stri="s(ss)",
      sig=70, depth=2, rkind=49
    ),
    @Meta.SymV(
      offset=4766, name=@Meta.QName(pack="io.github.mchav.freoquiz.Types", base="asTextView"), stri="s(ss)",
      sig=71, depth=2, rkind=49
    ),
    @Meta.SymV(
      offset=312, name=@Meta.QName(pack="io.github.mchav.freoquiz.Types", base="answerTextId"), stri="s",
      sig=9, nativ="io.github.mchav.freoquiz.R.id.answerTextView", pur=true, depth=0, rkind=33
    ),
    @Meta.SymV(
      offset=144, name=@Meta.QName(pack="io.github.mchav.freoquiz.Types", base="activityCheat"), stri="s",
      sig=9, nativ="io.github.mchav.freoquiz.R.layout.activity_cheat", pur=true, depth=0,
      rkind=33
    ),
    @Meta.SymV(
      offset=59, name=@Meta.QName(pack="io.github.mchav.freoquiz.Types", base="activityMain"), stri="s",
      sig=9, nativ="io.github.mchav.freoquiz.R.layout.activity_main", pur=true, depth=0,
      rkind=33
    )
  },
  symls={
    @Meta.SymL(
      offset=4053, name=@Meta.QName(pack="io.github.mchav.freoquiz.Types", base="downcast"),
      alias=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="CastTarget", member="downcast")
    ),
    @Meta.SymL(
      offset=1380, name=@Meta.QName(pack="io.github.mchav.freoquiz.Types", base="Question"),
      alias=@Meta.QName(kind=2, pack="io.github.mchav.freoquiz.Types", base="Question", member="Question")
    )
  },
  taus={
    @Meta.Tau(kind=9), @Meta.Tau(suba=0, tvar="a"),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeIO", base="Mutable")}),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="RealWorld")}),
    @Meta.Tau(kind=0, suba=2, subb=3),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="View")}),
    @Meta.Tau(kind=0, suba=4, subb=5),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="ST")}),
    @Meta.Tau(kind=0, suba=7, subb=3),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="Either")}),
    @Meta.Tau(
      kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="ClassCastException")}
    ),
    @Meta.Tau(kind=0, suba=9, subb=10), @Meta.Tau(kind=0, suba=4, subb=1), @Meta.Tau(kind=0, suba=11, subb=12),
    @Meta.Tau(kind=0, suba=8, subb=13),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="TextView")}),
    @Meta.Tau(kind=0, suba=4, subb=15), @Meta.Tau(kind=0, suba=11, subb=16), @Meta.Tau(kind=0, suba=8, subb=17),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="Button")}),
    @Meta.Tau(kind=0, suba=4, subb=19), @Meta.Tau(kind=0, suba=11, subb=20), @Meta.Tau(kind=0, suba=8, subb=21),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="Toolbar")}),
    @Meta.Tau(kind=0, suba=4, subb=23), @Meta.Tau(kind=0, suba=11, subb=24), @Meta.Tau(kind=0, suba=8, subb=25),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="Int")}),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="()")}),
    @Meta.Tau(kind=0, suba=8, subb=28),
    @Meta.Tau(
      kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="OnClickListener")}
    ),
    @Meta.Tau(kind=0, suba=4, subb=30),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="Toast")}),
    @Meta.Tau(kind=0, suba=4, subb=32),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="Context")}),
    @Meta.Tau(kind=0, suba=4, subb=34),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="StringJ")}),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="Char")}),
    @Meta.Tau(kind=0, suba=36, subb=37), @Meta.Tau(kind=0, suba=8, subb=33),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.java.Lang", base="CharSequence")}),
    @Meta.Tau(kind=0, suba=8, subb=40), @Meta.Tau(kind=0, suba=8, subb=16),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="Question")}),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="Bool")}),
    @Meta.Tau(suba=0, tvar="α"),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="->")}),
    @Meta.Tau(kind=0, suba=46, subb=38), @Meta.Tau(kind=0, suba=47, subb=38), @Meta.Tau(kind=0, suba=46, subb=44),
    @Meta.Tau(kind=0, suba=49, subb=44),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="MenuItem")}),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="Menu")}),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="Intent")}),
    @Meta.Tau(kind=0, suba=4, subb=53), @Meta.Tau(kind=0, suba=8, subb=54),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="Class")}),
    @Meta.Tau(kind=0, suba=56, subb=1), @Meta.Tau(kind=0, suba=8, subb=44), @Meta.Tau(suba=0, tvar="ω"),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="Bundle")}),
    @Meta.Tau(
      kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="AppCompatActivity")}
    ),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="Activity")}),
    @Meta.Tau(kind=0, suba=4, subb=62), @Meta.Tau(kind=0, suba=8, subb=6), @Meta.Tau(kind=0, suba=8, subb=35),
    @Meta.Tau(kind=0, suba=8, subb=31), @Meta.Tau(kind=0, suba=8, subb=20)
  },
  rhos={
    @Meta.Rho(rhofun=false, rhotau=6), @Meta.Rho(rhofun=false, rhotau=14),
    @Meta.Rho(
      cont={@Meta.Context(clas=@Meta.QName(kind=0, pack="io.github.mchav.freoquiz.Types", base="CastTarget"), tau=1)},
      sigma=0, rhotau=1
    ),
    @Meta.Rho(rhofun=false, rhotau=15), @Meta.Rho(rhofun=false, rhotau=18), @Meta.Rho(sigma=0, rhotau=4),
    @Meta.Rho(rhofun=false, rhotau=19), @Meta.Rho(rhofun=false, rhotau=22), @Meta.Rho(sigma=0, rhotau=7),
    @Meta.Rho(rhofun=false, rhotau=23), @Meta.Rho(rhofun=false, rhotau=26), @Meta.Rho(sigma=0, rhotau=10),
    @Meta.Rho(rhofun=false, rhotau=5), @Meta.Rho(rhofun=false, rhotau=27), @Meta.Rho(rhofun=false, rhotau=29),
    @Meta.Rho(sigma=9, rhotau=14), @Meta.Rho(sigma=0, rhotau=15), @Meta.Rho(rhofun=false, rhotau=31),
    @Meta.Rho(sigma=11, rhotau=14), @Meta.Rho(sigma=0, rhotau=18), @Meta.Rho(rhofun=false, rhotau=32),
    @Meta.Rho(rhofun=false, rhotau=33), @Meta.Rho(sigma=14, rhotau=14), @Meta.Rho(rhofun=false, rhotau=35),
    @Meta.Rho(rhofun=false, rhotau=38), @Meta.Rho(rhofun=false, rhotau=39), @Meta.Rho(sigma=9, rhotau=25),
    @Meta.Rho(sigma=17, rhotau=26), @Meta.Rho(sigma=16, rhotau=27), @Meta.Rho(rhofun=false, rhotau=16),
    @Meta.Rho(sigma=19, rhotau=15), @Meta.Rho(sigma=17, rhotau=14), @Meta.Rho(sigma=19, rhotau=31),
    @Meta.Rho(rhofun=false, rhotau=41), @Meta.Rho(sigma=19, rhotau=33), @Meta.Rho(rhofun=false, rhotau=42),
    @Meta.Rho(sigma=16, rhotau=35), @Meta.Rho(rhofun=false, rhotau=43), @Meta.Rho(rhofun=false, rhotau=44),
    @Meta.Rho(sigma=25, rhotau=37), @Meta.Rho(sigma=17, rhotau=39), @Meta.Rho(sigma=17, rhotau=37),
    @Meta.Rho(sigma=24, rhotau=41), @Meta.Rho(rhofun=false, rhotau=45), @Meta.Rho(sigma=28, rhotau=38),
    @Meta.Rho(sigma=24, rhotau=24), @Meta.Rho(sigma=24, rhotau=39), @Meta.Rho(rhofun=false, rhotau=48),
    @Meta.Rho(sigma=32, rhotau=37), @Meta.Rho(sigma=24, rhotau=48), @Meta.Rho(rhofun=false, rhotau=50),
    @Meta.Rho(sigma=34, rhotau=37), @Meta.Rho(sigma=24, rhotau=51), @Meta.Rho(sigma=24, rhotau=38),
    @Meta.Rho(rhofun=false, rhotau=30), @Meta.Rho(rhofun=false, rhotau=51), @Meta.Rho(rhofun=false, rhotau=52),
    @Meta.Rho(rhofun=false, rhotau=53), @Meta.Rho(rhofun=false, rhotau=54), @Meta.Rho(sigma=25, rhotau=14),
    @Meta.Rho(sigma=17, rhotau=59), @Meta.Rho(sigma=41, rhotau=60), @Meta.Rho(rhofun=false, rhotau=28),
    @Meta.Rho(rhofun=false, rhotau=55), @Meta.Rho(sigma=43, rhotau=63), @Meta.Rho(rhofun=false, rhotau=57),
    @Meta.Rho(sigma=45, rhotau=63), @Meta.Rho(sigma=16, rhotau=66), @Meta.Rho(rhofun=false, rhotau=58),
    @Meta.Rho(sigma=25, rhotau=68), @Meta.Rho(sigma=17, rhotau=69), @Meta.Rho(sigma=41, rhotau=70),
    @Meta.Rho(rhofun=false, rhotau=59), @Meta.Rho(rhofun=false, rhotau=34), @Meta.Rho(rhofun=false, rhotau=10),
    @Meta.Rho(rhofun=false, rhotau=20), @Meta.Rho(sigma=51, rhotau=15), @Meta.Rho(sigma=51, rhotau=33),
    @Meta.Rho(sigma=51, rhotau=18), @Meta.Rho(rhofun=false, rhotau=60), @Meta.Rho(rhofun=false, rhotau=61),
    @Meta.Rho(rhofun=false, rhotau=62), @Meta.Rho(rhofun=false, rhotau=63), @Meta.Rho(sigma=41, rhotau=15),
    @Meta.Rho(sigma=58, rhotau=83), @Meta.Rho(sigma=58, rhotau=15), @Meta.Rho(sigma=41, rhotau=14),
    @Meta.Rho(sigma=9, rhotau=86), @Meta.Rho(sigma=58, rhotau=87), @Meta.Rho(rhofun=false, rhotau=24),
    @Meta.Rho(sigma=62, rhotau=14), @Meta.Rho(sigma=58, rhotau=90), @Meta.Rho(rhofun=false, rhotau=64),
    @Meta.Rho(sigma=9, rhotau=92), @Meta.Rho(sigma=58, rhotau=93), @Meta.Rho(rhofun=false, rhotau=65),
    @Meta.Rho(sigma=58, rhotau=95), @Meta.Rho(sigma=58, rhotau=63), @Meta.Rho(sigma=0, rhotau=14),
    @Meta.Rho(rhofun=false, rhotau=66), @Meta.Rho(sigma=67, rhotau=99), @Meta.Rho(sigma=67, rhotau=14),
    @Meta.Rho(sigma=0, rhotau=101), @Meta.Rho(rhofun=false, rhotau=67), @Meta.Rho(sigma=9, rhotau=103),
    @Meta.Rho(sigma=58, rhotau=104), @Meta.Rho(sigma=9, rhotau=35), @Meta.Rho(sigma=58, rhotau=106)
  },
  sigmas={
    @Meta.Sigma(rho=0), @Meta.Sigma(bound={"a"}, kinds={0}, rho=2), @Meta.Sigma(rho=3), @Meta.Sigma(rho=5),
    @Meta.Sigma(rho=6), @Meta.Sigma(rho=8), @Meta.Sigma(rho=9), @Meta.Sigma(rho=11), @Meta.Sigma(rho=12),
    @Meta.Sigma(rho=13), @Meta.Sigma(rho=16), @Meta.Sigma(rho=17), @Meta.Sigma(rho=19), @Meta.Sigma(rho=20),
    @Meta.Sigma(rho=21), @Meta.Sigma(rho=22), @Meta.Sigma(rho=23), @Meta.Sigma(rho=24), @Meta.Sigma(rho=28),
    @Meta.Sigma(rho=29), @Meta.Sigma(rho=30), @Meta.Sigma(rho=32), @Meta.Sigma(rho=34), @Meta.Sigma(rho=36),
    @Meta.Sigma(rho=37), @Meta.Sigma(rho=38), @Meta.Sigma(rho=40), @Meta.Sigma(rho=42), @Meta.Sigma(rho=43),
    @Meta.Sigma(bound={"α"}, kinds={0}, rho=44), @Meta.Sigma(rho=45), @Meta.Sigma(rho=46), @Meta.Sigma(rho=47),
    @Meta.Sigma(rho=49), @Meta.Sigma(rho=50), @Meta.Sigma(rho=52), @Meta.Sigma(rho=53), @Meta.Sigma(rho=54),
    @Meta.Sigma(rho=55), @Meta.Sigma(rho=56), @Meta.Sigma(rho=57), @Meta.Sigma(rho=58), @Meta.Sigma(rho=61),
    @Meta.Sigma(rho=62), @Meta.Sigma(rho=64), @Meta.Sigma(rho=65), @Meta.Sigma(bound={"a"}, kinds={0}, rho=67),
    @Meta.Sigma(rho=71), @Meta.Sigma(bound={"ω"}, kinds={0}, rho=72), @Meta.Sigma(rho=73), @Meta.Sigma(rho=74),
    @Meta.Sigma(rho=75), @Meta.Sigma(rho=76), @Meta.Sigma(rho=77), @Meta.Sigma(rho=78), @Meta.Sigma(rho=79),
    @Meta.Sigma(rho=80), @Meta.Sigma(rho=81), @Meta.Sigma(rho=82), @Meta.Sigma(rho=84), @Meta.Sigma(rho=85),
    @Meta.Sigma(rho=88), @Meta.Sigma(rho=89), @Meta.Sigma(rho=91), @Meta.Sigma(rho=94), @Meta.Sigma(rho=96),
    @Meta.Sigma(rho=97), @Meta.Sigma(rho=98), @Meta.Sigma(rho=100), @Meta.Sigma(rho=102), @Meta.Sigma(rho=105),
    @Meta.Sigma(rho=107)
  },
  exprs={@Meta.Expr()}
)
final public class Types  {
  

public static android.view.View.OnClickListener
onClickHandler(final frege.run7.Func.U<android.view.View, frege.run7.Func.U<RealWorld,Short>> lambda) {
return new android.view.View.OnClickListener() {
@Override
public void onClick(android.view.View view) {
try {
final frege.run7.Func.U<Object,Short> res = RunTM.<frege.run7.Func.U<Object,Short>>cast(lambda.apply(Thunk.lazy(view)).call()).call();
frege.prelude.PreludeBase.TST.run(res).call();
} catch(RuntimeException re) {
re.printStackTrace();
throw re;
}
}
};
}

public interface CCastTarget<𝓐>  {
  public Func.U<RealWorld, PreludeBase.TEither<java.lang.ClassCastException, 𝓐>> ƒdowncast(
    final Lazy<android.view.View> arg$1
  ) ;
}
final public static class ICastTarget_TextView implements CCastTarget<android.widget.TextView> {
  public ICastTarget_TextView() {}
  final public static ICastTarget_TextView it = new ICastTarget_TextView();
  @Override final public Func.U<
    RealWorld, PreludeBase.TEither<java.lang.ClassCastException, android.widget.TextView>
  > ƒdowncast(final Lazy<android.view.View> arg$1) {
    return ICastTarget_TextView.downcast(arg$1.call());
  }
  final public static Func.U<RealWorld, PreludeBase.TEither<java.lang.ClassCastException, android.widget.TextView>> downcast(
    final android.view.View arg$1
  ) {
    return new Func.U.D<RealWorld, PreludeBase.TEither<java.lang.ClassCastException, android.widget.TextView>>() {
          public Lazy<PreludeBase.TEither<java.lang.ClassCastException, android.widget.TextView>> apply(
            final Lazy<RealWorld> _state
          ) {
            try {
              return PreludeBase.TEither.DRight.<java.lang.ClassCastException, android.widget.TextView>mk(
                        Thunk.<android.widget.TextView>lazy((android.widget.TextView)(arg$1))
                      );
            }
            catch (java.lang.ClassCastException ex) {
              return PreludeBase.TEither.DLeft.<java.lang.ClassCastException, android.widget.TextView>mk(
                        Thunk.<java.lang.ClassCastException>lazy(ex)
                      );
            }
          }
        };
  }
}
final public static class ICastTarget_Button implements CCastTarget<android.widget.Button> {
  public ICastTarget_Button() {}
  final public static ICastTarget_Button it = new ICastTarget_Button();
  @Override final public Func.U<RealWorld, PreludeBase.TEither<java.lang.ClassCastException, android.widget.Button>> ƒdowncast(
    final Lazy<android.view.View> arg$1
  ) {
    return ICastTarget_Button.downcast(arg$1.call());
  }
  final public static Func.U<RealWorld, PreludeBase.TEither<java.lang.ClassCastException, android.widget.Button>> downcast(
    final android.view.View arg$1
  ) {
    return new Func.U.D<RealWorld, PreludeBase.TEither<java.lang.ClassCastException, android.widget.Button>>() {
          public Lazy<PreludeBase.TEither<java.lang.ClassCastException, android.widget.Button>> apply(
            final Lazy<RealWorld> _state
          ) {
            try {
              return PreludeBase.TEither.DRight.<java.lang.ClassCastException, android.widget.Button>mk(
                        Thunk.<android.widget.Button>lazy((android.widget.Button)(arg$1))
                      );
            }
            catch (java.lang.ClassCastException ex) {
              return PreludeBase.TEither.DLeft.<java.lang.ClassCastException, android.widget.Button>mk(
                        Thunk.<java.lang.ClassCastException>lazy(ex)
                      );
            }
          }
        };
  }
}
final public static class ICastTarget_Toolbar implements CCastTarget<android.widget.Toolbar> {
  public ICastTarget_Toolbar() {}
  final public static ICastTarget_Toolbar it = new ICastTarget_Toolbar();
  @Override final public Func.U<RealWorld, PreludeBase.TEither<java.lang.ClassCastException, android.widget.Toolbar>> ƒdowncast(
    final Lazy<android.view.View> arg$1
  ) {
    return ICastTarget_Toolbar.downcast(arg$1.call());
  }
  final public static Func.U<RealWorld, PreludeBase.TEither<java.lang.ClassCastException, android.widget.Toolbar>> downcast(
    final android.view.View arg$1
  ) {
    return new Func.U.D<RealWorld, PreludeBase.TEither<java.lang.ClassCastException, android.widget.Toolbar>>() {
          public Lazy<PreludeBase.TEither<java.lang.ClassCastException, android.widget.Toolbar>> apply(
            final Lazy<RealWorld> _state
          ) {
            try {
              return PreludeBase.TEither.DRight.<java.lang.ClassCastException, android.widget.Toolbar>mk(
                        Thunk.<android.widget.Toolbar>lazy((android.widget.Toolbar)(arg$1))
                      );
            }
            catch (java.lang.ClassCastException ex) {
              return PreludeBase.TEither.DLeft.<java.lang.ClassCastException, android.widget.Toolbar>mk(
                        Thunk.<java.lang.ClassCastException>lazy(ex)
                      );
            }
          }
        };
  }
}
final public static class TView  {
  final public static Func.U<RealWorld, Short> setVisibility(final android.view.View arg$1, final int arg$2) {
    return new Func.U.D<RealWorld, Short>() {
          public Lazy<Short> apply(final Lazy<RealWorld> _state) {
            arg$1.setVisibility(arg$2);
            return Thunk.lazyUnit;
          }
        };
  }
  final public static Func.U<RealWorld, Short> setOnClickListener(
    final android.view.View arg$1, final android.view.View.OnClickListener arg$2
  ) {
    return new Func.U.D<RealWorld, Short>() {
          public Lazy<Short> apply(final Lazy<RealWorld> _state) {
            arg$1.setOnClickListener(arg$2);
            return Thunk.lazyUnit;
          }
        };
  }
}
final public static class TToast  {
  final public static Func.U<RealWorld, Short> show(final android.widget.Toast arg$1) {
    return new Func.U.D<RealWorld, Short>() {
          public Lazy<Short> apply(final Lazy<RealWorld> _state) {
            arg$1.show();
            return Thunk.lazyUnit;
          }
        };
  }
  final public static Func.U<RealWorld, android.widget.Toast> makeText(
    final android.content.Context arg$1, final String/*<Character>*/ arg$2, final int arg$3
  ) {
    return new Func.U.D<RealWorld, android.widget.Toast>() {
          public Lazy<android.widget.Toast> apply(final Lazy<RealWorld> _state) {
            return Thunk.<android.widget.Toast>lazy(android.widget.Toast.makeText(arg$1, arg$2, arg$3));
          }
        };
  }
}
final public static class TToolbar  {
  
}
final public static class TTextView  {
  final public static Func.U<RealWorld, Short> setVisibility(final android.widget.TextView arg$1, final int arg$2) {
    return new Func.U.D<RealWorld, Short>() {
          public Lazy<Short> apply(final Lazy<RealWorld> _state) {
            arg$1.setVisibility(arg$2);
            return Thunk.lazyUnit;
          }
        };
  }
  final public static Func.U<RealWorld, Short> setText(final android.widget.TextView arg$1, final String/*<Character>*/ arg$2) {
    return new Func.U.D<RealWorld, Short>() {
          public Lazy<Short> apply(final Lazy<RealWorld> _state) {
            arg$1.setText(arg$2);
            return Thunk.lazyUnit;
          }
        };
  }
  final public static Func.U<RealWorld, CharSequence> getText(final android.widget.TextView arg$1) {
    return new Func.U.D<RealWorld, CharSequence>() {
          public Lazy<CharSequence> apply(final Lazy<RealWorld> _state) {
            return Thunk.<CharSequence>lazy(arg$1.getText());
          }
        };
  }
  final public static Func.U<RealWorld, android.widget.TextView> $new(final android.content.Context arg$1) {
    return new Func.U.D<RealWorld, android.widget.TextView>() {
          public Lazy<android.widget.TextView> apply(final Lazy<RealWorld> _state) {
            return Thunk.<android.widget.TextView>lazy(new android.widget.TextView(arg$1));
          }
        };
  }
}
final public static class TQuestion implements frege.runtime.Value, Lazy<TQuestion> {
  private TQuestion(final Lazy<String/*<Character>*/> arg$1, final Lazy<Boolean> arg$2) {
    mem$text = Thunk.<String/*<Character>*/>shared(arg$1);
    mem$answer = Thunk.<Boolean>shared(arg$2);
  }
  final public int constructor() {
    return 0;
  }
  final public static TQuestion mk(final Lazy<String/*<Character>*/> arg$1, final Lazy<Boolean> arg$2) {
    return new TQuestion(arg$1, arg$2);
  }
  final public Lazy<String/*<Character>*/> mem$text  ;
  final public Lazy<Boolean> mem$answer  ;
  final public TQuestion call() {
    return this;
  }
  final public boolean isShared() {
    return true;
  }
  final public Thunk<TQuestion> asThunk() {
    return null;
  }
  @SuppressWarnings("unchecked") final public TQuestion simsalabim() {
    return (TQuestion)this;
  }
  final public static TQuestion upd$text(final TQuestion arg$1, final Lazy<String/*<Character>*/> arg$2) {
    return TQuestion.mk(arg$2, arg$1.mem$answer);
  }
  final public static <α> boolean has$text(final Lazy<α> arg$1) {
    return true;
  }
  final public static String/*<Character>*/ text(final TQuestion arg$1) {
    final String/*<Character>*/ a1$7665 = arg$1.mem$text.call();
    return a1$7665;
  }
  final public static TQuestion upd$answer(final TQuestion arg$1, final Lazy<Boolean> arg$2) {
    return TQuestion.mk(arg$1.mem$text, arg$2);
  }
  final public static TQuestion chg$text(
    final TQuestion arg$1, final Func.U<String/*<Character>*/, String/*<Character>*/> arg$2
  ) {
    return TQuestion.mk(
              Thunk.<String/*<Character>*/>nested(
                    new Lazy.D<Lazy<String/*<Character>*/>>() {
                      public Lazy<String/*<Character>*/> call() {
                        return arg$2.apply(arg$1.mem$text);
                      }
                    }
                  ),
              arg$1.mem$answer
            );
  }
  final public static TQuestion chg$answer(final TQuestion arg$1, final Func.U<Boolean, Boolean> arg$2) {
    return TQuestion.mk(
              arg$1.mem$text,
              Thunk.<Boolean>nested(
                    new Lazy.D<Lazy<Boolean>>() {
                      public Lazy<Boolean> call() {
                        return arg$2.apply(arg$1.mem$answer);
                      }
                    }
                  )
            );
  }
  final public static boolean answer(final TQuestion arg$1) {
    final boolean a2$7654 = (boolean)arg$1.mem$answer.call();
    return a2$7654;
  }
  final public static <α> boolean has$answer(final Lazy<α> arg$1) {
    return true;
  }
}
final public static class TIntent  {
  final public static Func.U<RealWorld, Short> putExtra(
    final android.content.Intent arg$1, final String/*<Character>*/ arg$2, final boolean arg$3
  ) {
    return new Func.U.D<RealWorld, Short>() {
          public Lazy<Short> apply(final Lazy<RealWorld> _state) {
            arg$1.putExtra(arg$2, arg$3);
            return Thunk.lazyUnit;
          }
        };
  }
  final public static Func.U<RealWorld, android.content.Intent> newα(final short arg$1) {
    return new Func.U.D<RealWorld, android.content.Intent>() {
          public Lazy<android.content.Intent> apply(final Lazy<RealWorld> _state) {
            return Thunk.<android.content.Intent>lazy(new android.content.Intent());
          }
        };
  }
  final public static <𝓐> Func.U<RealWorld, android.content.Intent> newβ(
    final android.content.Context arg$1, final Class<𝓐> arg$2
  ) {
    return new Func.U.D<RealWorld, android.content.Intent>() {
          public Lazy<android.content.Intent> apply(final Lazy<RealWorld> _state) {
            return Thunk.<android.content.Intent>lazy(new android.content.Intent(arg$1, arg$2));
          }
        };
  }
  final public static Func.U<RealWorld, Boolean> getBooleanExtra(
    final android.content.Intent arg$1, final String/*<Character>*/ arg$2, final boolean arg$3
  ) {
    return new Func.U.D<RealWorld, Boolean>() {
          public Lazy<Boolean> apply(final Lazy<RealWorld> _state) {
            return Thunk.<Boolean>lazy(arg$1.getBooleanExtra(arg$2, arg$3));
          }
        };
  }
}
final public static class TButton  {
  final public static Func.U<RealWorld, Short> setVisibility(final android.widget.Button arg$1, final int arg$2) {
    return new Func.U.D<RealWorld, Short>() {
          public Lazy<Short> apply(final Lazy<RealWorld> _state) {
            arg$1.setVisibility(arg$2);
            return Thunk.lazyUnit;
          }
        };
  }
  final public static Func.U<RealWorld, CharSequence> getText(final android.widget.Button arg$1) {
    return new Func.U.D<RealWorld, CharSequence>() {
          public Lazy<CharSequence> apply(final Lazy<RealWorld> _state) {
            return Thunk.<CharSequence>lazy(arg$1.getText());
          }
        };
  }
  final public static Func.U<RealWorld, Short> setOnClickListener(
    final android.widget.Button arg$1, final android.view.View.OnClickListener arg$2
  ) {
    return new Func.U.D<RealWorld, Short>() {
          public Lazy<Short> apply(final Lazy<RealWorld> _state) {
            arg$1.setOnClickListener(arg$2);
            return Thunk.lazyUnit;
          }
        };
  }
}
final public static class TActivity  {
  final public static Func.U<RealWorld, Short> startActivityForResult(
    final android.app.Activity arg$1, final android.content.Intent arg$2, final int arg$3
  ) {
    return new Func.U.D<RealWorld, Short>() {
          public Lazy<Short> apply(final Lazy<RealWorld> _state) {
            arg$1.startActivityForResult(arg$2, arg$3);
            return Thunk.lazyUnit;
          }
        };
  }
  final public static Func.U<RealWorld, Short> setContentView(final android.app.Activity arg$1, final int arg$2) {
    return new Func.U.D<RealWorld, Short>() {
          public Lazy<Short> apply(final Lazy<RealWorld> _state) {
            arg$1.setContentView(arg$2);
            return Thunk.lazyUnit;
          }
        };
  }
  final public static Func.U<RealWorld, Short> setResult(
    final android.app.Activity arg$1, final int arg$2, final android.content.Intent arg$3
  ) {
    return new Func.U.D<RealWorld, Short>() {
          public Lazy<Short> apply(final Lazy<RealWorld> _state) {
            arg$1.setResult(arg$2, arg$3);
            return Thunk.lazyUnit;
          }
        };
  }
  final public static Func.U<RealWorld, Short> setActionBar(
    final android.app.Activity arg$1, final android.widget.Toolbar arg$2
  ) {
    return new Func.U.D<RealWorld, Short>() {
          public Lazy<Short> apply(final Lazy<RealWorld> _state) {
            arg$1.setActionBar(arg$2);
            return Thunk.lazyUnit;
          }
        };
  }
  final public static Func.U<RealWorld, android.view.View> findViewById(final android.app.Activity arg$1, final int arg$2) {
    return new Func.U.D<RealWorld, android.view.View>() {
          public Lazy<android.view.View> apply(final Lazy<RealWorld> _state) {
            return Thunk.<android.view.View>lazy(arg$1.findViewById(arg$2));
          }
        };
  }
  final public static Func.U<RealWorld, android.content.Context> getApplicationContext(
    final android.app.Activity arg$1
  ) {
    return new Func.U.D<RealWorld, android.content.Context>() {
          public Lazy<android.content.Context> apply(final Lazy<RealWorld> _state) {
            return Thunk.<android.content.Context>lazy(arg$1.getApplicationContext());
          }
        };
  }
  final public static Func.U<RealWorld, android.content.Intent> getIntent(final android.app.Activity arg$1) {
    return new Func.U.D<RealWorld, android.content.Intent>() {
          public Lazy<android.content.Intent> apply(final Lazy<RealWorld> _state) {
            return Thunk.<android.content.Intent>lazy(arg$1.getIntent());
          }
        };
  }
}
final public static String/*<Character>*/ packageName = "io.github.mchav.freoquiz";
final public static Func.U<RealWorld, android.view.View.OnClickListener> onClick(
  final Func.U<android.view.View, Func.U<RealWorld, Short>> arg$1
) {
  return new Func.U.D<RealWorld, android.view.View.OnClickListener>() {
        public Lazy<android.view.View.OnClickListener> apply(final Lazy<RealWorld> _state) {
          return Thunk.<android.view.View.OnClickListener>lazy(io.github.mchav.freoquiz.Types.onClickHandler(arg$1));
        }
      };
}
final public static Func.U<RealWorld, Short> attachHandler(
  final Lazy<android.view.View> arg$1, final Func.U<android.view.View, Func.U<RealWorld, Short>> arg$2
) {
  final Func.U<RealWorld, android.view.View.OnClickListener> v2038$7825 = Types.onClick(
        arg$2
      );
  return new Func.U.D<RealWorld, Short>() {
        public Lazy<Short> apply(final Lazy<RealWorld> arg$7950) {
          final android.view.View.OnClickListener v2041$7828 = v2038$7825.apply(arg$7950)
          .call();
          final Func.U<RealWorld, Short> v2042$7829 = TView.setOnClickListener(arg$1.call(), v2041$7828);
          return Thunk.<Short>nested(
                    new Lazy.D<Lazy<Short>>() {
                      public Lazy<Short> call() {
                        return v2042$7829.apply(arg$7950);
                      }
                    }
                  );
        }
      };
}
final public static Func.U<RealWorld, android.widget.TextView> asTextView(final android.app.Activity arg$1, final int arg$2) {
  final Func.U<RealWorld, android.view.View> v2038$7898 = TActivity.findViewById(arg$1, arg$2);
  return new Func.U.D<RealWorld, android.widget.TextView>() {
        public Lazy<android.widget.TextView> apply(final Lazy<RealWorld> arg$7954) {
          final android.view.View v2041$7901 = v2038$7898.apply(arg$7954).call();
          final Func.U<RealWorld, PreludeBase.TEither<java.lang.ClassCastException, android.widget.TextView>> v2038$7920 =
          ICastTarget_TextView.downcast(v2041$7901);
          final PreludeBase.TEither<java.lang.ClassCastException, android.widget.TextView> v2041$7923 =
          v2038$7920.apply(arg$7954).call();
          final Func.U<RealWorld, android.widget.TextView> v2042$7924 = PreludeBase.<
            Func.U<RealWorld, android.widget.TextView>, java.lang.ClassCastException, android.widget.TextView
          >either(
                new Func.U.D<java.lang.ClassCastException, Func.U<RealWorld, android.widget.TextView>>() {
                  public Lazy<Func.U<RealWorld, android.widget.TextView>> apply(
                    final Lazy<java.lang.ClassCastException> arg$7958
                  ) {
                    return Thunk.<Func.U<RealWorld, android.widget.TextView>>shared(
                              new Lazy.D<Func.U<RealWorld, android.widget.TextView>>() {
                                public Func.U<RealWorld, android.widget.TextView> call() {
                                  return PreludeBase.<Func.U<RealWorld, android.widget.TextView>>error(
                                            "Cast failed."
                                          );
                                }
                              }
                            );
                  }
                },
                new Func.U.D<android.widget.TextView, Func.U<RealWorld, android.widget.TextView>>() {
                  public Lazy<Func.U<RealWorld, android.widget.TextView>> apply(final Lazy<android.widget.TextView> η$7959) {
                    return Thunk.<Func.U<RealWorld, android.widget.TextView>>shared(
                              new Lazy.D<Func.U<RealWorld, android.widget.TextView>>() {
                                public Func.U<RealWorld, android.widget.TextView> call() {
                                  return PreludeMonad.IMonad_ST.<RealWorld, android.widget.TextView>pure(
                                            η$7959
                                          );
                                }
                              }
                            );
                  }
                },
                v2041$7923
              ).call();
          return Thunk.<android.widget.TextView>nested(
                    new Lazy.D<Lazy<android.widget.TextView>>() {
                      public Lazy<android.widget.TextView> call() {
                        return v2042$7924.apply(arg$7954);
                      }
                    }
                  );
        }
      };
}
final public static Func.U<RealWorld, android.widget.Button> asButton(final android.app.Activity arg$1, final int arg$2) {
  final Func.U<RealWorld, android.view.View> v2038$7847 = TActivity.findViewById(arg$1, arg$2);
  return new Func.U.D<RealWorld, android.widget.Button>() {
        public Lazy<android.widget.Button> apply(final Lazy<RealWorld> arg$7962) {
          final android.view.View v2041$7850 = v2038$7847.apply(arg$7962).call();
          final Func.U<RealWorld, PreludeBase.TEither<java.lang.ClassCastException, android.widget.Button>> v2038$7869 =
          ICastTarget_Button.downcast(v2041$7850);
          final PreludeBase.TEither<java.lang.ClassCastException, android.widget.Button> v2041$7872 =
          v2038$7869.apply(arg$7962).call();
          final Func.U<RealWorld, android.widget.Button> v2042$7873 = PreludeBase.<
            Func.U<RealWorld, android.widget.Button>, java.lang.ClassCastException, android.widget.Button
          >either(
                new Func.U.D<java.lang.ClassCastException, Func.U<RealWorld, android.widget.Button>>() {
                  public Lazy<Func.U<RealWorld, android.widget.Button>> apply(
                    final Lazy<java.lang.ClassCastException> arg$7966
                  ) {
                    return Thunk.<Func.U<RealWorld, android.widget.Button>>shared(
                              new Lazy.D<Func.U<RealWorld, android.widget.Button>>() {
                                public Func.U<RealWorld, android.widget.Button> call() {
                                  return PreludeBase.<Func.U<RealWorld, android.widget.Button>>error(
                                            "Cast failed."
                                          );
                                }
                              }
                            );
                  }
                },
                new Func.U.D<android.widget.Button, Func.U<RealWorld, android.widget.Button>>() {
                  public Lazy<Func.U<RealWorld, android.widget.Button>> apply(final Lazy<android.widget.Button> η$7967) {
                    return Thunk.<Func.U<RealWorld, android.widget.Button>>shared(
                              new Lazy.D<Func.U<RealWorld, android.widget.Button>>() {
                                public Func.U<RealWorld, android.widget.Button> call() {
                                  return PreludeMonad.IMonad_ST.<RealWorld, android.widget.Button>pure(
                                            η$7967
                                          );
                                }
                              }
                            );
                  }
                },
                v2041$7872
              ).call();
          return Thunk.<android.widget.Button>nested(
                    new Lazy.D<Lazy<android.widget.Button>>() {
                      public Lazy<android.widget.Button> call() {
                        return v2042$7873.apply(arg$7962);
                      }
                    }
                  );
        }
      };
}

}
